In [1]:
import cv2
import numpy as np
import pandas as pd

In [2]:
img = cv2.imread('./lena.jpg', cv2.IMREAD_GRAYSCALE)
# 20,30 위치의 밝기 값을 val에 저장
val = img[30,20]

#200, 100위치의 밝기 값을 50으로 설정
img[100,200] = 50

cv2.imshow('new', img)
cv2.waitKey()
cv2.destroyAllWindows()

In [5]:
img[30]

array([157, 157, 158, 159, 159, 159, 159, 159, 159, 160, 157, 161, 162,
       159, 160, 158, 157, 161, 159, 161, 161, 161, 163, 161, 163, 165,
       166, 167, 167, 167, 168, 168, 167, 167, 166, 166, 167, 167, 165,
       163, 162, 159, 161, 161, 156, 157, 160, 158, 160, 163, 164, 164,
       166, 163, 159, 158, 146, 140, 140, 133, 128, 117, 110, 101,  97,
        90,  91,  88,  84,  86,  88,  91,  97, 102, 100,  99,  96, 104,
       105, 106, 107, 104, 107, 105, 109, 104, 103,  99, 106, 108, 105,
       101, 102, 103, 102, 104, 106, 109, 101, 102, 102, 107, 105, 110,
       107, 108, 107, 107, 110, 111, 113, 117, 115, 118, 119, 122, 122,
       123, 122, 123, 124, 124, 123, 127, 127, 127, 124, 124, 125, 129,
       124, 126, 126, 128, 124, 129, 129, 128, 134, 126, 126, 124, 124,
       125, 128, 127, 130, 127, 131, 127, 130, 128, 128, 128, 129, 128,
       131, 127, 128, 131, 129, 129, 132, 134, 130, 128, 129, 128, 130,
       135, 129, 130, 131, 127, 131, 130, 131, 128, 133, 131, 13

In [11]:
print(len(img[30]))
print(len(img[:,20]))
print(img[30,20])
img_bgr = cv2.imread('./lena.jpg')
print(img_bgr[30,20])

512
512
161
[111 136 228]


In [13]:
img[100]

array([ 89,  88,  81,  83,  86,  93,  91,  94,  90,  87,  88,  90,  90,
        91,  90,  86,  92,  95,  91,  86,  88,  88,  86,  89,  92, 100,
       110, 115, 125, 127, 136, 144, 147, 150, 156, 160, 161, 160, 162,
       166, 167, 168, 168, 166, 164, 164, 164, 164, 169, 165, 166, 163,
       162, 160, 151, 148, 144, 140, 137, 127, 122, 112, 107,  95,  94,
        81,  74,  73,  76,  78,  77,  82,  87,  85,  90,  93,  96,  98,
        95,  97,  94, 105, 106, 103,  98, 106, 106, 103,  98, 102, 102,
        99,  98, 101, 103, 101,  94, 101, 105, 103, 108, 101, 104, 100,
       106, 105, 107, 109, 110, 112, 112, 108, 109, 110, 114, 114, 117,
       113, 114, 114, 117, 118, 121, 121, 120, 116, 117, 118, 124, 116,
       119, 121, 121, 120, 133, 142, 140, 122, 110, 105, 107, 110, 107,
       109, 107, 111, 118, 117, 121, 110, 108, 109, 109, 109, 111, 110,
       112, 114, 114, 123, 116, 120, 119, 123, 113, 107, 121, 122, 122,
       122, 126, 125, 115, 119, 128, 117, 117, 119, 123, 132, 13

In [15]:
cv2.imshow('new', img[90:110, 190:210])
cv2.waitKey()
cv2.destroyAllWindows()

In [19]:
img = cv2.imread('./lena.jpg', cv2.IMREAD_GRAYSCALE)
(h,w) = img.shape
print(h,w)
(cy,cx) = (h//2, w//2)
print(cy,cx)

#왼쪽 위 원점부터 중간점까지 사각형 영역을 ROI에 저장
roi = img[0:cy, 0:cx]

cv2.imshow('img', img)
cv2.imshow('ROI', roi)
cv2.waitKey()
cv2.destroyAllWindows()

512 512
256 256


In [27]:
#레나 얼굴만

img = cv2.imread('./lena.jpg', cv2.IMREAD_GRAYSCALE)
(h,w) = img.shape
print(h,w)
(cy,cx) = (h//2, w//2)
(hs,ws) = cy//2, cx//2
(he,we) = cy+hs, cx+ws
print(hs,ws)

roi_f = img[hs:he, ws:we]

cv2.imshow('img', img)
cv2.imshow('ROI', roi_f)
cv2.waitKey()
cv2.destroyAllWindows()

512 512
128 128


In [ ]:
# 레나 점

img = cv2.imread('./lena.jpg', cv2.IMREAD_GRAYSCALE)

dst = img.copy()
dst = 

cv2.imshow('img', img)
cv2.imshow('p', p)
cv2.waitKey()
cv2.destroyAllWindows()

In [33]:
# copy
src = cv2.imread('./lena.jpg', 0)
dst = src.copy()
(h,w) = dst.shape
(cy,cx) = (h//2, w//2)
(hs,ws) = cy//2, cx//2
(he,we) = cy+hs, cx+ws

dst[hs:he,ws:we] = 0
cv2.imshow('src', src)
cv2.imshow('dst', dst)
cv2.waitKey()
cv2.destroyAllWindows()

In [46]:
# src 영상을 각각 b, g, r 층으로 copy해서 컬러로 변환

src = cv2.imread('./lena.jpg')
bw = cv2.imread('./lena.jpg', 0)

color = src[0]


cv2.imshow('src', src)
cv2.imshow('bw', bw)
cv2.waitKey()
cv2.destroyAllWindows()
bw

array([[163, 162, 161, ..., 170, 154, 130],
       [162, 162, 162, ..., 173, 155, 126],
       [162, 162, 163, ..., 170, 155, 128],
       ...,
       [ 43,  42,  51, ..., 103, 101,  99],
       [ 41,  42,  55, ..., 103, 105, 106],
       [ 42,  44,  57, ..., 102, 106, 109]], dtype=uint8)

In [76]:
bw[0][0] = src[0][0]

ValueError: setting an array element with a sequence.

In [64]:
for i in range(len(src[0])):
    bw[0][i] = src[0][i]
    
print(bw[0])

ValueError: setting an array element with a sequence.

In [109]:
src = cv2.imread('./lena.jpg')
dst = cv2.imread('./lena.jpg')

h = dst.shape[0]
w = dst.shape[1]
(cy,cx) = (h//2, w//2)
(hs,ws) = cy//2, cx//2
(he,we) = cy+hs, cx+ws

dst[hs:he,ws:we] = [255,255,255]


cv2.imshow('src', src)
cv2.imshow('dst', dst)
cv2.waitKey()
cv2.destroyAllWindows()

In [11]:
import cv2
import numpy as np
import pandas as pd

src = cv2.imread('./lena.jpg')
dst = np.zeros([512,512,3])

dst[:, :, 0] = src[:,:,0]
dst[:, :, 1] = src[:,:,1]
dst[:, :, 2] = src[:,:,2]
dst_int = dst_int = dst.astype(np.uint8)

cv2.imshow('src', src)
cv2.imshow('dst', dst_int)
cv2.waitKey()
cv2.destroyAllWindows()
print(dst)

[[[128. 138. 225.]
  [127. 137. 224.]
  [126. 136. 224.]
  ...
  [126. 145. 236.]
  [110. 129. 220.]
  [ 86. 104. 197.]]

 [[127. 137. 224.]
  [127. 137. 224.]
  [127. 137. 224.]
  ...
  [130. 150. 235.]
  [112. 132. 217.]
  [ 83. 102. 189.]]

 [[127. 137. 224.]
  [127. 137. 224.]
  [128. 138. 225.]
  ...
  [127. 148. 230.]
  [111. 133. 215.]
  [ 84. 105. 190.]]

 ...

 [[ 55.  21.  82.]
  [ 54.  20.  81.]
  [ 62.  28.  92.]
  ...
  [ 82.  71. 175.]
  [ 78.  68. 175.]
  [ 74.  65. 175.]]

 [[ 53.  19.  80.]
  [ 54.  20.  81.]
  [ 66.  32.  96.]
  ...
  [ 82.  69. 177.]
  [ 80.  71. 181.]
  [ 81.  72. 183.]]

 [[ 54.  20.  81.]
  [ 56.  22.  83.]
  [ 68.  34.  98.]
  ...
  [ 81.  68. 176.]
  [ 81.  72. 183.]
  [ 84.  74. 188.]]]


In [12]:
src = cv2.imread('./lena.jpg',0)
dst = np.zeros([512,512,3])

dst[:, :, 0] = src.copy()
dst[:, :, 1] = src.copy()
dst[:, :, 2] = src.copy()

dst_int = dst.astype(np.uint8)
dst_int
cv2.imshow('src', src)
cv2.imshow('dst_int', dst_int)
cv2.waitKey()
cv2.destroyAllWindows()
print(dst_int)

[[[163 163 163]
  [162 162 162]
  [161 161 161]
  ...
  [170 170 170]
  [154 154 154]
  [130 130 130]]

 [[162 162 162]
  [162 162 162]
  [162 162 162]
  ...
  [173 173 173]
  [155 155 155]
  [126 126 126]]

 [[162 162 162]
  [162 162 162]
  [163 163 163]
  ...
  [170 170 170]
  [155 155 155]
  [128 128 128]]

 ...

 [[ 43  43  43]
  [ 42  42  42]
  [ 51  51  51]
  ...
  [103 103 103]
  [101 101 101]
  [ 99  99  99]]

 [[ 41  41  41]
  [ 42  42  42]
  [ 55  55  55]
  ...
  [103 103 103]
  [105 105 105]
  [106 106 106]]

 [[ 42  42  42]
  [ 44  44  44]
  [ 57  57  57]
  ...
  [102 102 102]
  [106 106 106]
  [109 109 109]]]


In [13]:
src = cv2.imread('./lena.jpg',0)
dst = np.zeros([512,512,3])

dst[:, :, 0] = src.copy()
dst[:, :, 1] = src.copy()
dst[:, :, 2] = src.copy()

dst[180:400,180:400] = [255,255,255]

dst_int = dst.astype(np.uint8)
dst_int
cv2.imshow('src', src)
cv2.imshow('dst_int', dst_int)
cv2.waitKey()
cv2.destroyAllWindows()
print(dst)

[[[163. 163. 163.]
  [162. 162. 162.]
  [161. 161. 161.]
  ...
  [170. 170. 170.]
  [154. 154. 154.]
  [130. 130. 130.]]

 [[162. 162. 162.]
  [162. 162. 162.]
  [162. 162. 162.]
  ...
  [173. 173. 173.]
  [155. 155. 155.]
  [126. 126. 126.]]

 [[162. 162. 162.]
  [162. 162. 162.]
  [163. 163. 163.]
  ...
  [170. 170. 170.]
  [155. 155. 155.]
  [128. 128. 128.]]

 ...

 [[ 43.  43.  43.]
  [ 42.  42.  42.]
  [ 51.  51.  51.]
  ...
  [103. 103. 103.]
  [101. 101. 101.]
  [ 99.  99.  99.]]

 [[ 41.  41.  41.]
  [ 42.  42.  42.]
  [ 55.  55.  55.]
  ...
  [103. 103. 103.]
  [105. 105. 105.]
  [106. 106. 106.]]

 [[ 42.  42.  42.]
  [ 44.  44.  44.]
  [ 57.  57.  57.]
  ...
  [102. 102. 102.]
  [106. 106. 106.]
  [109. 109. 109.]]]


In [14]:
dst[0,0] = [dst[0,0,0],dst[0,0,1], np.random.randint(0,255)]
dst[0,0]

array([163., 163.,  23.])

In [26]:
src = cv2.imread('./lena.jpg',0)
dst = np.zeros([512,512,3])

dst[:, :, 0] = src.copy()
dst[:, :, 1] = src.copy()
dst[:, :, 2] = src.copy()


for x in range(len(dst[0])):
    for y in range(len(dst[:,0])):
        dst[x,y] = [dst[x,y,0], dst[x,y,1],np.random.randint(0,255)]
cv2.imshow('src', src)
cv2.imshow('dst_int', np.uint8(dst))
cv2.waitKey()
cv2.destroyAllWindows()
print(np.uint8(dst))

[[[163 163  11]
  [162 162 225]
  [161 161 108]
  ...
  [170 170  97]
  [154 154  30]
  [130 130  96]]

 [[162 162 149]
  [162 162  99]
  [162 162  97]
  ...
  [173 173  94]
  [155 155  35]
  [126 126 225]]

 [[162 162  64]
  [162 162  93]
  [163 163 223]
  ...
  [170 170 162]
  [155 155  55]
  [128 128 155]]

 ...

 [[ 43  43  73]
  [ 42  42 243]
  [ 51  51 142]
  ...
  [103 103  33]
  [101 101 130]
  [ 99  99 147]]

 [[ 41  41 193]
  [ 42  42 161]
  [ 55  55 121]
  ...
  [103 103   6]
  [105 105 226]
  [106 106  21]]

 [[ 42  42   3]
  [ 44  44  20]
  [ 57  57   2]
  ...
  [102 102 101]
  [106 106 237]
  [109 109 216]]]


In [23]:
src = cv2.imread('./lena.jpg',0)
dst = np.zeros([512,512,3])

dst[:, :, 0] = src.copy()
dst[:, :, 1] = src.copy()
dst[:, :, 2] = src.copy()



for x in range(len(dst[0])):
    for y in range(len(dst[:,0])):
        dst[x,y] = [dst[x,y,0], np.random.randint(0,255) ,np.random.randint(0,255)]
cv2.imshow('src', src)
cv2.imshow('dst_int', np.uint8(dst))
cv2.waitKey()
cv2.destroyAllWindows()

In [24]:
src = cv2.imread('./lena.jpg',0)
dst = np.zeros([512,512,3])

dst[:, :, 0] = src.copy()
dst[:, :, 1] = src.copy()
dst[:, :, 2] = src.copy()



for x in range(len(dst[0])):
    for y in range(len(dst[:,0])):
        dst[x,y] = [np.random.randint(0,255), np.random.randint(0,255) ,np.random.randint(0,255)]
cv2.imshow('src', src)
cv2.imshow('dst_int', np.uint8(dst))
cv2.waitKey()
cv2.destroyAllWindows()


In [33]:
lena = './lena.jpg'
img = cv2.imread(lena)
rgbsp = cv2.split(img)
rgbmg = cv2.merge(rgbsp)
cv2.imshow('rgbmg', rgbmg)
cv2.waitKey()
cv2.destroyAllWindows()

In [34]:
lena = './lena.jpg'
img = cv2.imread(lena)
rgbsp = cv2.split(img)
print(type(rgbsp))
print(type(rgbsp[0]))
print(rgbsp[0])

<class 'tuple'>
<class 'numpy.ndarray'>
[[128 127 126 ... 126 110  86]
 [127 127 127 ... 130 112  83]
 [127 127 128 ... 127 111  84]
 ...
 [ 55  54  62 ...  82  78  74]
 [ 53  54  66 ...  82  80  81]
 [ 54  56  68 ...  81  81  84]]


In [35]:
b = img[:,:,0]
g = img[:,:,1]
r = img[:,:,2]

In [36]:
cv2.imshow('img', img)
cv2.imshow('blue', rgbsp[0])
cv2.imshow('green', rgbsp[1])
cv2.imshow('red', rgbsp[2])
cv2.imshow('b', b)
cv2.imshow('g', g)
cv2.imshow('r', r)
cv2.waitKey()
cv2.destroyAllWindows()
cv2.waitKey(1)

-1

In [38]:
new = np.zeros([512,512,3])
for x in range(512):
    for y in range(512):
        new[x,y] = [b[x,y], g[x,y], r[x,y]]

dst = cv2.merge([b,g,r])

cv2.imshow('self_merge', np.uint8(new))
cv2.imshow('func_merge', dst)
cv2.waitKey()
cv2.destroyAllWindows()
cv2.waitKey(1)

-1

In [60]:
lena = './lena.jpg'
src = cv2.imread(lena)
gray = cv2.cvtColor(src, cv2.COLOR_BGR2GRAY)
yCrCv = cv2.cvtColor(src, cv2.COLOR_BGR2YCrCb)
hsv = cv2.cvtColor(src, cv2.COLOR_BGR2HSV)

cv2.imshow('src', src)
cv2.imshow('gray', gray)
cv2.imshow('yCrCv', yCrCv)
cv2.imshow('hsv', hsv)
cv2.waitKey()
cv2.destroyAllWindows()

In [53]:
lena = './lena.jpg'
src = cv2.imread(lena, cv2.IMREAD_GRAYSCALE)
print(src.shape)

dst1 = cv2.resize(src, dsize=(320, 240))
dst2 = cv2.resize(src, dsize=(0,0), fx=1.5, fy=1.2)

cv2.imshow('dst1',dst1)
cv2.imshow('dst2', dst2)
cv2.waitKey()
cv2.destroyAllWindows()

(512, 512)


In [3]:
import cv2
import numpy as np
import pandas as pd

lena = './lena.jpg'
src = cv2.imread(lena, cv2.IMREAD_GRAYSCALE)
print(src.shape)

dst1 = cv2.resize(src, dsize=(800, 300))
dst2 = cv2.resize(src, dsize=(0,0), fx=1.5, fy=1.8)

print('dst1.shape', dst1.shape)
print('dst2.shape', dst2.shape)
cv2.imshow('dst1',dst1) #x, y 순서가 다름
cv2.imshow('dst2', dst2)
cv2.waitKey()
cv2.destroyAllWindows()



(512, 512)
dst1.shape (300, 800)
dst2.shape (922, 768)


In [4]:


lena = './lena.jpg'
src = cv2.imread(lena, cv2.IMREAD_GRAYSCALE)
print(src.shape)

dst3 = cv2.rotate(dst1, cv2.ROTATE_90_CLOCKWISE)
dst4 = cv2.rotate(dst2, cv2.ROTATE_90_COUNTERCLOCKWISE)
dst5 = cv2.rotate(dst3, cv2.ROTATE_90_CLOCKWISE)

cv2.imshow('dst3', dst3)
cv2.imshow('dst4', dst4)
cv2.imshow('dst5', dst5)
cv2.waitKey()
cv2.destroyAllWindows()

(512, 512)


In [14]:
src = cv2.imread(lena)
rows, cols, channels = src.shape

M1 = cv2.getRotationMatrix2D((rows/2, cols/2),45,0.3)
M2 = cv2.getRotationMatrix2D((rows/2, cols/2),-45,0.7)
dst1 = cv2.warpAffine(src, M1, (rows, cols))
dst2 = cv2.warpAffine(src, M2, (rows, cols))

cv2.imshow('dst1', dst1)
cv2.imshow('dst2', dst2)
cv2.waitKey()
cv2.destroyAllWindows()

In [15]:
pip install imutils

  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
  Created wheel for imutils: filename=imutils-0.5.4-py3-none-any.whl size=25872 sha256=e989207f802829ba59208a00a7acfb2b537fb21ba8aaac748765a2d0b2174781
  Stored in directory: c:\users\playdata\appdata\local\pip\cache\wheels\f4\4b\8b\a9c23da464a09c6ad0a131c1752079bc85f9f1677c7b78e87d
Successfully built imutils
Note: you may need to restart the kernel to use updated packages.


In [1]:
import imutils
import cv2
import numpy as np
import pandas as pd

In [19]:
image = './lena.jpg'
src = cv2.imread(image)

tran = imutils.translate(src, 10, 30)
rot = imutils.rotate(src, angle=10, center=(src.shape[0]//2,src.shape[1]//2))
res = imutils.resize(src, width=100, height=10000, inter=3)

cv2.imshow('translate',tran)
cv2.imshow('rotate',rot)
cv2.imshow('resize',res)
cv2.waitKey()
cv2.destroyAllWindows()

In [27]:
import imutils
src = cv2.imread('./lena.jpg')
rows, cols, channels = src.shape
dst1 = imutils.translate(src, 10, 30)
dst2 = imutils.rotate(src, angle=10, center=(rows/2, cols/2), scale=1.0)
dst3 = imutils.resize(src, width=800, height=100)
cv2.imshow('src', src)
cv2.imshow('dst', dst1)
cv2.imshow('dst2', dst2)
cv2.imshow('dst3', dst3)
cv2.waitKey()
cv2.destroyAllWindows()
cv2.waitKey(1)

-1

In [ ]:
# cv2.add(src1, src2)
# cv2.addWeighted(src1, alpha, src2, beta, gamma,)
# cv2.subtract(src1, src2)
# cv2.scaleAdd
# cv2.multiply
# cv2.divide

In [70]:
import imutils
import cv2
import numpy as np
import pandas as pd

lena = './lena.jpg'
src1 = cv2.imread(lena, cv2.IMREAD_GRAYSCALE)
src2 = np.zeros(shape=(512,512), dtype=np.uint8) + 100

dst1 = src1 + src2
dst2 = cv2.add(src1, src2)

cv2.imshow('dst1', dst1)
cv2.imshow('dst2', dst2)
cv2.waitKey()
cv2.destroyAllWindows()

In [51]:
src1 = cv2.imread('./lena.jpg')
src2 = cv2.imread('./baboon.jpg')

dst1 = cv2.addWeighted(src1, 0.2, scr2, 0.8,0)
dst2 = cv2.addWeighted(src1, 0.5, scr2, 0.5,0)

cv2.imshow('dst1', dst1)
cv2.imshow('dst2', dst2)
cv2.waitKey()
cv2.destroyAllWindows()

In [52]:
print(src1[:2,:2])
print(src2[:2,:2])

[[[128 138 225]
  [127 137 224]]

 [[127 137 224]
  [127 137 224]]]
[[[106 148 160]
  [ 15  60  71]]

 [[ 53 112 131]
  [ 54 106 123]]]


In [53]:
cv2.addWeighted(src1[:2,:2], 0.2, src2[:2,:2], 0.8,0)

array([[[110, 146, 173],
        [ 37,  75, 102]],

       [[ 68, 117, 150],
        [ 69, 112, 143]]], dtype=uint8)

In [54]:
cv2.addWeighted(src1[:2,:2], 0.5, src2[:2,:2], 0.5,0)

array([[[117, 143, 192],
        [ 71,  98, 148]],

       [[ 90, 124, 178],
        [ 90, 122, 174]]], dtype=uint8)

In [69]:
src = cv2.imread('./lena.jpg', cv2.IMREAD_GRAYSCALE)
ret, dst = cv2.threshold(src, 130, 255, cv2.THRESH_BINARY)
print('ret =', ret)

cv2.imshow('src', src)
cv2.imshow('dst', dst)
cv2.waitKey()
cv2.destroyAllWindows()

ret = 130.0


In [71]:
src = cv2.imread('./lena.jpg', cv2.IMREAD_GRAYSCALE)
ret, dst = cv2.threshold(src, 120, 255, cv2.THRESH_BINARY_INV)
print('ret =', ret)

cv2.imshow('src', src)
cv2.imshow('dst', dst)
cv2.waitKey()
cv2.destroyAllWindows()

ret = 120.0


In [92]:
src = cv2.imread('./cup.png', 0)
ret, dst = cv2.threshold(src, 185, 255, cv2.THRESH_BINARY)
print('ret =', ret)

cv2.imshow('src', src)
cv2.imshow('dst', dst)
cv2.waitKey()
cv2.destroyAllWindows()

ret = 185.0


In [84]:
src = cv2.imread('./cup.png')
ret, dst = cv2.threshold(src, 185, 255, cv2.THRESH_BINARY)
print('ret =', ret)

cv2.imshow('src', src)
cv2.imshow('dst', dst)
cv2.waitKey()
cv2.destroyAllWindows()

ret = 120.0


In [95]:
src = cv2.imread('./cup.png',0)
ret, dst = cv2.threshold(src, 185, 255, cv2.THRESH_BINARY_INV)
print('ret =', ret)

cv2.imshow('src', src)
cv2.imshow('dst', dst)
cv2.waitKey()
cv2.destroyAllWindows()

ret = 185.0


In [105]:
src = cv2.imread('./cup.png',0)
ret, dst = cv2.threshold(src, 255, 255, cv2.THRESH_TRUNC)
print('ret =', ret)

cv2.imshow('src', src)
cv2.imshow('dst', dst)
cv2.waitKey()
cv2.destroyAllWindows()

ret = 255.0


In [119]:
src = cv2.imread('./cup.png',0)
ret, dst = cv2.threshold(src, 190, 255, cv2.THRESH_TOZERO)
print('ret =', ret)

cv2.imshow('src', src)
cv2.imshow('dst', dst)
cv2.waitKey()
cv2.destroyAllWindows()

ret = 190.0


In [114]:
src = cv2.imread('./cup.png',0)
ret, dst = cv2.threshold(src, 180, 255, cv2.THRESH_TOZERO_INV)
print('ret =', ret)

cv2.imshow('src', src)
cv2.imshow('dst', dst)
cv2.waitKey()
cv2.destroyAllWindows()

ret = 180.0


In [161]:
src = cv2.imread('./opencv_logo.png', 0)
ret, dst = cv2.threshold(src, 200, 255, cv2.THRESH_BINARY)

cv2.imshow('src', src)
cv2.imshow('dst', dst)
cv2.waitKey()
cv2.destroyAllWindows()

In [159]:
src = cv2.imread('./opencv_logo.png')
ret, dst = cv2.threshold(src, 150, 255, cv2.THRESH_BINARY_INV)

cv2.imshow('src', src)
cv2.imshow('dst', dst)
cv2.waitKey()
cv2.destroyAllWindows()

In [162]:
src = cv2.imread('./opencv_logo.png', 0)
ret, dst = cv2.threshold(src, 200, 255, cv2.THRESH_BINARY_INV)

cv2.imshow('src', src)
cv2.imshow('dst', dst)
cv2.waitKey()
cv2.destroyAllWindows()

In [158]:
#### src = cv2.imread('./opencv_logo.png',)
ret, dst = cv2.threshold(src,50, 255, cv2.THRESH_TOZERO)

cv2.imshow('src', src)
cv2.imshow('dst', dst)
cv2.waitKey()
cv2.destroyAllWindows()

In [165]:
src1 = cv2.imread('./lena.jpg',0)
src2 = np.zeros(shape=(512,512), dtype=np.uint8) + 255

print(src1[0,:10])
print(src2[0,:10])

[163 162 161 160 163 157 163 162 165 161]
[255 255 255 255 255 255 255 255 255 255]


In [166]:
dst1 = 255-src1 #inverse
print(src1[0,:10])
print(dst1[0,:10])

[163 162 161 160 163 157 163 162 165 161]
[92 93 94 95 92 98 92 93 90 94]


In [167]:
dst2 = cv2.subtract(src2, src1)
print(src1[0,:10])
print(dst2[0,:10])

[163 162 161 160 163 157 163 162 165 161]
[92 93 94 95 92 98 92 93 90 94]


In [169]:
dst3 = cv2.compare(dst1, dst2, cv2.CMP_EQ)
print(src1[0,:10])
print(dst3[0,:10])

[163 162 161 160 163 157 163 162 165 161]
[255 255 255 255 255 255 255 255 255 255]


In [170]:
dst4 = cv2.compare(dst1, dst2, cv2.CMP_NE)
print(src1[0,:10])
print(dst4[0,:10])

[163 162 161 160 163 157 163 162 165 161]
[0 0 0 0 0 0 0 0 0 0]


In [171]:
dst5 = cv2.compare(dst1, dst2, cv2.CMP_GT)
print(src1[0,:10])
print(dst5[0,:10])

[163 162 161 160 163 157 163 162 165 161]
[0 0 0 0 0 0 0 0 0 0]


In [172]:
dst6 = cv2.compare(dst1, dst2, cv2.CMP_GE)
print(src1[0,:10])
print(dst6[0,:10])

[163 162 161 160 163 157 163 162 165 161]
[255 255 255 255 255 255 255 255 255 255]


In [173]:
dst7 = cv2.compare(dst1, dst2, cv2.CMP_LT)
print(src1[0,:10])
print(dst7[0,:10])

[163 162 161 160 163 157 163 162 165 161]
[0 0 0 0 0 0 0 0 0 0]


In [174]:
dst8 = cv2.compare(dst1, dst2, cv2.CMP_LE)
print(src1[0,:10])
print(dst8[0,:10])

[163 162 161 160 163 157 163 162 165 161]
[255 255 255 255 255 255 255 255 255 255]


In [176]:
cv2.imshow('src1', src1)
cv2.imshow('dst1', dst1)
cv2.imshow('dst2', dst2)
cv2.imshow('dst3', dst3)
cv2.imshow('dst4', dst4)
cv2.imshow('dst5', dst5)
cv2.imshow('dst6', dst6)
cv2.imshow('dst7', dst7)
cv2.imshow('dst8', dst8)

cv2.waitKey()
cv2.destroyAllWindows()