In [4]:
import cv2
import numpy as np
import matplotlib.pyplot as plt

In [5]:
src = cv2.imread('/Users/iseung-won/lena.jpg', cv2.IMREAD_GRAYSCALE)
ret, bina = cv2.threshold(src, 120, 255, cv2.THRESH_BINARY)

kernel = cv2.getStructuringElement(shape=cv2.MORPH_RECT, ksize=(3,3))

ero = cv2.erode(bina, kernel, iterations=1)
dil = cv2.dilate(bina, kernel, iterations=1)
open1 = cv2.morphologyEx(bina, cv2.MORPH_OPEN, kernel, iterations=1)
close1 = cv2.morphologyEx(bina, cv2.MORPH_CLOSE, kernel, iterations=1)
tophat1 = cv2.morphologyEx(bina, cv2.MORPH_TOPHAT, kernel, iterations=1)
blackhat1 = cv2.morphologyEx(bina, cv2.MORPH_BLACKHAT, kernel, iterations=1)

cv2.imshow('binary', bina)
cv2.imshow('erode', ero)
cv2.imshow('dilate', dil)
cv2.imshow('open', open1)
cv2.imshow('close', close1)
cv2.imshow('tophat', tophat1)
cv2.imshow('blackhat', blackhat1)

cv2.waitKey()
cv2.destroyAllWindows()
cv2.waitKey(1)

-1

In [29]:
src = cv2.imread('/Users/iseung-won/lena.jpg', cv2.IMREAD_GRAYSCALE)
ret, bina = cv2.threshold(src, 0, 255, cv2.THRESH_BINARY+cv2.THRESH_OTSU)

kernel = cv2.getStructuringElement(shape=cv2.MORPH_RECT, ksize=(3,3))

ero = cv2.erode(bina, kernel, iterations=1)
dil = cv2.dilate(bina, kernel, iterations=1)
open1 = cv2.morphologyEx(bina, cv2.MORPH_OPEN, kernel, iterations=1)
close1 = cv2.morphologyEx(bina, cv2.MORPH_CLOSE, kernel, iterations=1)
gradient1 = cv2.morphologyEx(bina, cv2.MORPH_GRADIENT, kernel)
tophat1 = cv2.morphologyEx(bina, cv2.MORPH_TOPHAT, kernel, iterations=1)
blackhat1 = cv2.morphologyEx(bina, cv2.MORPH_BLACKHAT, kernel, iterations=1)

cv2.imshow('binary', bina)
cv2.imshow('erode', ero)
cv2.imshow('dilate', dil)
cv2.imshow('open', open1)
cv2.imshow('close', close1)
cv2.imshow('gradient', gradient1)
cv2.imshow('tophat', tophat1)
cv2.imshow('blackhat', blackhat1)

cv2.waitKey()
cv2.destroyAllWindows()
cv2.waitKey(1)

-1

In [32]:
src = cv2.imread('/Users/iseung-won/lena.jpg', cv2.IMREAD_GRAYSCALE)
ret, bina = cv2.threshold(src, 0, 255, cv2.THRESH_BINARY+cv2.THRESH_OTSU)

kernel = cv2.getStructuringElement(shape=cv2.MORPH_RECT, ksize=(3,3))

ero = cv2.erode(bina, kernel, iterations=2)
dil = cv2.dilate(bina, kernel, iterations=2)
open1 = cv2.morphologyEx(bina, cv2.MORPH_OPEN, kernel, iterations=2)
close1 = cv2.morphologyEx(bina, cv2.MORPH_CLOSE, kernel, iterations=2)
gradient1 = cv2.morphologyEx(bina, cv2.MORPH_GRADIENT, kernel)
tophat1 = cv2.morphologyEx(bina, cv2.MORPH_TOPHAT, kernel, iterations=2)
blackhat1 = cv2.morphologyEx(bina, cv2.MORPH_BLACKHAT, kernel, iterations=2)

cv2.imshow('binary', bina)
cv2.imshow('erode', ero)
cv2.imshow('dilate', dil)
cv2.imshow('open', open1)
cv2.imshow('close', close1)
cv2.imshow('gradient', gradient1)
cv2.imshow('tophat', tophat1)
cv2.imshow('blackhat', blackhat1)

cv2.waitKey()
cv2.destroyAllWindows()
cv2.waitKey(1)

-1

In [33]:
import cv2
src = cv2.imread('/Users/iseung-won/lena.jpg', 0)
ret, dst = cv2.threshold(src, 0, 255, cv2.THRESH_BINARY+cv2.THRESH_OTSU)
i = 2 # 2 이상부터 입이 없어진다
kernel = cv2.getStructuringElement(shape=cv2.MORPH_RECT, ksize=(3,3))
erode = cv2.morphologyEx(dst, cv2.MORPH_ERODE, kernel, iterations = i)
dilate = cv2.morphologyEx(dst, cv2.MORPH_DILATE, kernel, iterations = i)
closing = cv2.morphologyEx(dst, cv2.MORPH_CLOSE, kernel, iterations = i)
opening = cv2.morphologyEx(closing, cv2.MORPH_OPEN, kernel, iterations = i)
gradient = cv2.morphologyEx(opening, cv2.MORPH_GRADIENT, kernel)
tophat = cv2.morphologyEx(dst, cv2.MORPH_TOPHAT, kernel, iterations = i)
blackhat = cv2.morphologyEx(dst, cv2.MORPH_BLACKHAT, kernel, iterations = i)
cv2.imshow('blackhat', blackhat)
cv2.imshow('tophat', tophat)
cv2.imshow('gradient', gradient)
cv2.imshow('closing', closing)
cv2.imshow('opening', opening)
cv2.imshow('dilate', dilate)
cv2.imshow('erode', erode)
cv2.imshow('dst', dst)
cv2.waitKey()
cv2.destroyAllWindows()
cv2.waitKey(1)

-1

In [2]:
import cv2
import numpy as np
import matplotlib.pyplot as plt

In [92]:
src = cv2.imread('/Users/iseung-won/circles.jpg', cv2.IMREAD_GRAYSCALE)

ret, dst = cv2.threshold(src, 0, 255, cv2.THRESH_BINARY+cv2.THRESH_OTSU) #0과 255로 극과 극으로 나눔
dst_r = cv2.bitwise_not(dst) #0과 255 밝기를 반전 시켜줌
cnt, labels, stats, centroid = cv2.connectedComponentsWithStats(dst_r) # 정보 저장



font = cv2.FONT_HERSHEY_SIMPLEX
x1 = 400
y1 = 170
size1 = 121,121
angle1 = 0

x2 = 250
y2 = 250
size2 = 141,141
angle2 = 0

x3 = 350
y3 = 400
size3 = 101,101
angle3 = 0

rect1 = ((x1,y1), size1, angle1)
rect2 = ((x2,y2), size2, angle2)
rect3 = ((x3,y3), size3, angle3)




cv2.putText(dst,'label=1', (340, 110), font, 1, (150,0,255), 2)
cv2.putText(dst,'label=2', (180, 180), font, 1, (150,0,255), 2)
cv2.putText(dst,'label=3', (300, 350), font, 1, (150,0,255), 2)
box1 = cv2.boxPoints(rect1).astype(np.int32)
box2 = cv2.boxPoints(rect2).astype(np.int32)
box3 = cv2.boxPoints(rect3).astype(np.int32)

cv2.rectangle(dst, (0,0), (512,512), 0, 3)
cv2.polylines(dst, [box1], True, (0,0,0), 2)
cv2.polylines(dst, [box2], True, (0,0,0), 2)
cv2.polylines(dst, [box3], True, (0,0,0), 2)
cv2.circle(dst, (400,170), 1, (255,255,255), 6)
cv2.circle(dst, (250,250), 1, (255,255, 255), 6)
cv2.circle(dst, (350,400), 1, (255,255,255), 6)

for i in range(1, cnt): # 각각의 객체 정보에 들어가기 위해 반복문. 범위를 1부터 시작한 이유는 배경을 제외
    (x, y, width, height, area) = stats[i]
    print('x =', x)
    print('y =', y)
    print('width =', width)
    print('height =', height)
    print('area =', area)
    print('centroid =', centroid)
    


cv2.imshow('src', src)
cv2.imshow('dst', dst)
cv2.imshow('rev', dst_r)

cv2.waitKey()
cv2.destroyAllWindows()
cv2.waitKey(1)


print('ret', ret)
print('labels', np.unique(labels))

x = 340
y = 110
width = 121
height = 121
area = 11289
centroid = [[245.44863972 255.13168773]
 [400.         170.        ]
 [250.         250.        ]
 [350.         400.        ]]
x = 180
y = 180
width = 141
height = 141
area = 15373
centroid = [[245.44863972 255.13168773]
 [400.         170.        ]
 [250.         250.        ]
 [350.         400.        ]]
x = 300
y = 350
width = 101
height = 101
area = 7845
centroid = [[245.44863972 255.13168773]
 [400.         170.        ]
 [250.         250.        ]
 [350.         400.        ]]
ret 10.0
labels [0 1 2 3]


In [6]:
dst_f = cv2.imread('/Users/iseung-won/circles.jpg')

font = cv2.FONT_HERSHEY_SIMPLEX
x1 = 400
y1 = 170
size1 = 121,121
angle1 = 0

x2 = 250
y2 = 250
size2 = 141,141
angle2 = 0

x3 = 350
y3 = 400
size3 = 101,101
angle3 = 0

rect1 = ((x1,y1), size1, angle1)
rect2 = ((x2,y2), size2, angle2)
rect3 = ((x3,y3), size3, angle3)


cv2.putText(dst_f,'label=1', (340, 110), font, 1, (255,0,0), 2)
cv2.putText(dst_f,'label=2', (180, 180), font, 1, (255,0,0), 2)
cv2.putText(dst_f,'label=3', (300, 350), font, 1, (255,0,0), 2)
box1 = cv2.boxPoints(rect1).astype(np.int32)
box2 = cv2.boxPoints(rect2).astype(np.int32)
box3 = cv2.boxPoints(rect3).astype(np.int32)

cv2.rectangle(dst_f, (0,0), (512,512), (255,0,0), 10)
cv2.polylines(dst_f, [box1], True, (0,0,255), 2)
cv2.polylines(dst_f, [box2], True, (0,0,255), 2)
cv2.polylines(dst_f, [box3], True, (0,0,255), 2)
cv2.circle(dst_f, (400,170), 1, (0,0,255), 3)
cv2.circle(dst_f, (250,250), 1, (0,0,255), 3)
cv2.circle(dst_f, (350,400), 1, (0,0,255), 3)
cv2.circle(dst_f, (245,255), 1, (255,0,0), 6)

    


cv2.imshow('final', dst_f)


cv2.waitKey()
cv2.destroyAllWindows()
cv2.waitKey(1)

-1

In [9]:
# 강사님 코드

import cv2
import numpy as np
# Circle 영상에 컨버트 칼라와 쓰레스홀드를 주었다.
src = cv2.imread('/Users/iseung-won/circles.jpg')
gray = cv2.cvtColor(src, cv2.COLOR_BGR2GRAY)
ret, res = cv2.threshold(gray, 128, 255, cv2.THRESH_BINARY_INV) # Thresh binary inverse를 걸었다.
# 그래서 검은게 하얀색으로 하얀게 검은색으로 바뀌었다.
cv2.imshow('src', src)
cv2.imshow('res', res)
cv2.waitKey()
cv2.destroyAllWindows()
cv2.waitKey(1)
# 이 CCL 적용하면 우리가 원하는 것은 1, 2, 3 레이블링 하는 것, 컴포넌트 레이블링을 한다.

-1

In [11]:
ret, labels = cv2.connectedComponents(res)
print('ret=', ret)
print('labels', np.unique(labels))
labels = cv2.normalize(src=labels, dst=labels, alpha=0, beta=255, norm_type=cv2.NORM_MINMAX, dtype=cv2.CV_8U)
print('norm labels', np.unique(labels))
cv2.imshow('src', src)
cv2.imshow('labels', labels)
cv2.waitKey()
cv2.destroyAllWindows()
cv2.waitKey(1)
# 이건 그냥 커넥티드 컴포넌트를 한 것이므로 이거 보다는 아래에 있는 것을 하는 게 낳지 않을까

ret= 4
labels [0 1 2 3]
norm labels [  0  85 170 255]


-1

In [12]:
# 이걸 하게 되면 바로 끝이 난다. 영역과 무게 중심을 다 찾아 줍니다.
ret, labels, stats, centroids = cv2.connectedComponentsWithStats(res)
print('ret=', ret)
print('labels=', np.unique(labels))
print('stats=', stats)
print('centroids=', centroids)
dst = src.copy()
cv2.circle(dst, (int(centroids[0][0]), int(centroids[0][1])), radius=5, color=(255,0,0), thickness=-1)
cv2.circle(dst, (int(centroids[1][0]), int(centroids[1][1])), radius=3, color=(0,0,255), thickness=-1)
cv2.circle(dst, (int(centroids[2][0]), int(centroids[2][1])), radius=3, color=(0,0,255), thickness=-1)
cv2.circle(dst, (int(centroids[3][0]), int(centroids[3][1])), radius=3, color=(0,0,255), thickness=-1)
cv2.rectangle(dst, (stats[0][0], stats[0][1]), (stats[0][0]+stats[0][2], stats[0][1]+stats[0][3]), [255,0,0], 5)
cv2.rectangle(dst, (stats[1][0], stats[1][1]), (stats[1][0]+stats[1][2], stats[1][1]+stats[1][3]), [0,0,255])
cv2.rectangle(dst, (stats[2][0], stats[2][1]), (stats[2][0]+stats[2][2], stats[2][1]+stats[2][3]), [0,0,255])
cv2.rectangle(dst, (stats[3][0], stats[3][1]), (stats[3][0]+stats[3][2], stats[3][1]+stats[3][3]), [0,0,255])
font = cv2.FONT_HERSHEY_SIMPLEX
cv2.putText(dst, 'label=1', (stats[1][0], stats[1][1]), font, 0.5, (255, 0, 0), 1)
cv2.putText(dst, 'label=2', (stats[2][0], stats[2][1]), font, 0.5, (255, 0, 0), 1)
cv2.putText(dst, 'label=3', (stats[3][0], stats[3][1]), font, 0.5, (255, 0, 0), 1)
cv2.imshow('src', src)
cv2.imshow('dst', dst)
cv2.waitKey()
cv2.destroyAllWindows()
cv2.waitKey(1)

ret= 4
labels= [0 1 2 3]
stats= [[     0      0    512    512 227637]
 [   340    110    121    121  11289]
 [   180    180    141    141  15373]
 [   300    350    101    101   7845]]
centroids= [[245.44863972 255.13168773]
 [400.         170.        ]
 [250.         250.        ]
 [350.         400.        ]]


-1

In [102]:
# 2차 미분 가우시안 블러 적용 후 

import cv2
import numpy as np
src = cv2.imread('/Users/iseung-won/lena.jpg', 0)

dstg1 = cv2.GaussianBlur(src, ksize=(3,3), sigmaX=0.0, borderType=cv2.BORDER_CONSTANT)
dstg2 = cv2.GaussianBlur(src, ksize=(3,3), sigmaX=10.0, borderType=cv2.BORDER_CONSTANT)
dstg3 = cv2.GaussianBlur(src, ksize=(3,3), sigmaX=1.0, sigmaY=10.0, borderType=cv2.BORDER_CONSTANT)

lap1 = cv2.Laplacian(dstg1, cv2.CV_32F)
lap2 = cv2.Laplacian(dstg2, cv2.CV_32F)
lap3 = cv2.Laplacian(dstg3, cv2.CV_32F)


dst1 = cv2.convertScaleAbs(lap1)
dst2 = cv2.convertScaleAbs(lap2)
dst3 = cv2.convertScaleAbs(lap3)

dst_n1 = cv2.normalize(dst1, None, 0, 255, cv2.NORM_MINMAX)
dst_n2 = cv2.normalize(dst2, None, 0, 255, cv2.NORM_MINMAX)
dst_n3 = cv2.normalize(dst3, None, 0, 255, cv2.NORM_MINMAX)

gx = cv2.Sobel(src, ddepth=cv2.CV_32F, dx=1, dy=0, ksize=3)
gy = cv2.Sobel(src, ddepth=cv2.CV_32F, dx=0, dy=1, ksize=3)
mag = cv2.magnitude(gx, gy)
dstM = cv2.normalize(mag, 0, 255, norm_type=cv2.NORM_MINMAX, dtype=cv2.CV_8U)


cv2.imshow('dstM', dstM)
cv2.imshow('dst1', dst1)
# cv2.imshow('dst_n1', dst_n1)
# cv2.imshow('dst_n2', dst_n2)
# cv2.imshow('dst_n3', dst_n3)
cv2.waitKey()
cv2.destroyAllWindows()
cv2.waitKey(1)

-1

In [13]:

src = cv2.imread('/Users/iseung-won/lena.jpg', cv2.IMREAD_GRAYSCALE)
dstg = cv2.GaussianBlur(src, ksize=(3,3), sigmaX=0.0, borderType=cv2.BORDER_CONSTANT)

gx = cv2.Sobel(dstg, ddepth=cv2.CV_32F, dx=1, dy=0, ksize=3)
gy = cv2.Sobel(dstg, ddepth=cv2.CV_32F, dx=0, dy=1, ksize=3)
combine = gx.astype(np.uint8) + gy.astype(np.uint8)

# gxc = cv2.Canny(gx.astype(np.uint8), 150, 160)
# gyc = cv2.Canny(gy.astype(np.uint8), 150, 160)
gcc150_160 = cv2.Canny(combine, 150, 160)
gcc200_210 = cv2.Canny(combine, 200, 210)
gcc230_240 = cv2.Canny(combine, 230,240)
gcc200_201 = cv2.Canny(combine, 200, 201)
gcc254_255 = cv2.Canny(combine, 254, 255)
gcc170_180 = cv2.Canny(combine, 150, 151)

mag = cv2.magnitude(gx, gy)
dstM = cv2.normalize(mag, 0, 255, norm_type=cv2.NORM_MINMAX, dtype=cv2.CV_8U)

cv2.imshow('dstg', dstg)
cv2.imshow('dstM', dstM)
cv2.imshow('combine', combine)
# cv2.imshow('gyx', gxc)
# cv2.imshow('gyc', gyc)
cv2.imshow('gcc150_160', gcc150_160)
cv2.imshow('gcc200_210', gcc200_210)
cv2.imshow('gcc230_240', gcc230_240)
cv2.imshow('gcc200_201', gcc200_201)
cv2.imshow('gcc254_255', gcc254_255)
cv2.imshow('gcc170_180', gcc170_180)
cv2.waitKey()
cv2.destroyAllWindows()
cv2.waitKey(1)


# 캐니는 원본 파일에다가 하는 거라고 함
#괘니 가우시안 쓰고 가져다 붙이고 한듯

-1

In [146]:
src = cv2.imread('/Users/iseung-won/lena.jpg', cv2.IMREAD_GRAYSCALE)
dstg = cv2.GaussianBlur(src, ksize=(3,3), sigmaX=0.0, borderType=cv2.BORDER_CONSTANT)

gx = cv2.Sobel(dstg, ddepth=cv2.CV_32F, dx=1, dy=0, ksize=3)
gy = cv2.Sobel(dstg, ddepth=cv2.CV_32F, dx=0, dy=1, ksize=3)

mag = cv2.magnitude(gx, gy)
dstM = cv2.normalize(mag, 0, 255, norm_type=cv2.NORM_MINMAX, dtype=cv2.CV_8U)

gcc150_200 = cv2.Canny(src, 150, 200)
gcc50_200 = cv2.Canny(src, 50, 200)
gcc100_200 = cv2.Canny(src, 100, 200)
cv2.imshow('dstM', dstM)
cv2.imshow('gcc150_200', gcc150_200)
cv2.imshow('gcc50_200', gcc50_200)
cv2.imshow('gcc100_200', gcc100_200)
cv2.waitKey()
cv2.destroyAllWindows()
cv2.waitKey(1)

-1

In [14]:
# 강사님 코드

import cv2
import numpy as np
src = cv2.imread('/Users/iseung-won/lena.jpg', cv2.IMREAD_GRAYSCALE)
gx = cv2.Sobel(src, cv2.CV_32F, 1, 0, ksize=3) # x 방향 미분
gy = cv2.Sobel(src, cv2.CV_32F, 0, 1, ksize=3) # y 방향 미분
mag = cv2.magnitude(gx, gy)
dstM = cv2.normalize(mag, 0, 255, cv2.NORM_MINMAX)
edges1 = cv2.Canny(src, 50, 100)
edges2 = cv2.Canny(src, 50, 200)
cv2.imshow('src', src)
cv2.imshow('mag', dstM)
cv2.imshow('edges1', edges1)
cv2.imshow('edges2', edges2)
cv2.waitKey()
cv2.destroyAllWindows()
cv2.waitKey(1)

-1

In [15]:
src = cv2.imread('/Users/iseung-won/rect.jpg', cv2.IMREAD_GRAYSCALE)
edges = cv2.Canny(src, 50, 200)
hl = cv2.HoughLines(edges, rho=1, theta=np.pi/180.0, threshold=50)
hlp = cv2.HoughLinesP(edges, rho=1, theta=np.pi/180.0, threshold=50)

cv2.imshow('edges', edges)
# cv2.imshow('hl', hl)
# cv2.imshow('hlp', hlp)

# cv2.waitKey()
# cv2.destroyAllWindows()
# cv2.waitKey(1)
print(hl)
print(hlp)

[[[ 3.0000000e+02  0.0000000e+00]]

 [[ 1.9900000e+02  0.0000000e+00]]

 [[ 1.9900000e+02  1.5707964e+00]]

 [[ 3.0000000e+02  1.5707964e+00]]

 [[ 2.9600000e+02  1.5882496e+00]]

 [[ 1.9500000e+02  1.5882496e+00]]

 [[-2.9600000e+02  3.1241393e+00]]

 [[-1.9500000e+02  3.1241393e+00]]

 [[ 2.0300000e+02  1.7453292e-02]]

 [[ 3.0400000e+02  1.7453292e-02]]

 [[ 2.0300000e+02  1.5533431e+00]]

 [[ 3.0400000e+02  1.5533431e+00]]]
[[[199 296 199 201]]

 [[300 296 300 200]]

 [[200 300 294 300]]

 [[201 199 296 199]]]


In [24]:
src = cv2.imread('/Users/iseung-won/rect.jpg', cv2.IMREAD_GRAYSCALE)

edges = cv2.Canny(src,50,150,apertureSize=3)

hlp = cv2.HoughLinesP(edges, rho=1, theta=np.pi/180.0, threshold=50)

hl = cv2.HoughLines(edges, rho=1, theta=np.pi/180.0, threshold=50)

for line in hl:
    rho, theta, threshold = hl
    a = np.cos(theta)
    b = np.sin(theta)
    x0 = a*rho
    y0 = b*rho
    x1 = int(x0+1000*(-b))
    y1 = int(y0+1000*(a))
    x2 = int(x0-1000*(-b))    
    y2 = int(y0-1000*(a))    

cv2.line(src,(x1,y1),(x2,y2),(0,0,255),2)


cv2.imshow('edges', edges)
cv2.imshow('src', src)
# cv2.imshow('hlp', hlp)

cv2.waitKey()
cv2.destroyAllWindows()
cv2.waitKey(1)
print(hl)
print(hlp)



ValueError: too many values to unpack (expected 3)

In [18]:
src = cv2.imread('/Users/iseung-won/rect.jpg', cv2.IMREAD_GRAYSCALE)

edges = cv2.Canny(src,50,150,apertureSize=3)

lines = cv2.HoughLinesP(edges, rho=1, theta=np.pi/180.0, threshold=50)
print('lines.shape =', lines.shape)
# hl = cv2.HoughLines(edges, rho=1, theta=np.pi/180.0, threshold=50)




cv2.line(src,(x1,y1),(x2,y2),(0,0,255),2)


cv2.imshow('edges', edges)
cv2.imshow('src', src)
# cv2.imshow('hlp', hlp)

cv2.waitKey()
cv2.destroyAllWindows()
cv2.waitKey(1)
print(hl)
print(hlp)




lines.shape = (4, 1, 4)
[[[ 3.0000000e+02  0.0000000e+00]]

 [[ 1.9900000e+02  0.0000000e+00]]

 [[ 1.9900000e+02  1.5707964e+00]]

 [[ 3.0000000e+02  1.5707964e+00]]

 [[ 2.9600000e+02  1.5882496e+00]]

 [[ 1.9500000e+02  1.5882496e+00]]

 [[-2.9600000e+02  3.1241393e+00]]

 [[-1.9500000e+02  3.1241393e+00]]

 [[ 2.0300000e+02  1.7453292e-02]]

 [[ 3.0400000e+02  1.7453292e-02]]

 [[ 2.0300000e+02  1.5533431e+00]]

 [[ 3.0400000e+02  1.5533431e+00]]]
[[[199 296 199 201]]

 [[300 296 300 200]]

 [[200 300 294 300]]

 [[201 199 296 199]]]


In [165]:
# 강사님 코드

src = cv2.imread('/Users/iseung-won/rect.jpg')
gray = cv2.cvtColor(src, cv2.COLOR_BGR2GRAY)
# 캐니 에지
edges = cv2.Canny(gray, 30, 70)
# xy 평면을 rho theta 평면 변환
lines = cv2.HoughLinesP(edges, rho=1, theta=np.pi/180.0, threshold=50)
print('lines.shape=', lines.shape)
for line in lines:
    x1, y1, x2, y2 = line[0]
    cv2.line(src, (x1, y1), (x2, y2), (0, 0, 255), 2)
cv2.imshow('canny', edges)
cv2.imshow('src', src)
cv2.waitKey()
cv2.destroyAllWindows()
cv2.waitKey(1)

lines.shape= (4, 1, 4)


-1

In [181]:
# 강사님 코드

src = cv2.imread('/Users/iseung-won/rect.jpg')
gray = cv2.cvtColor(src, cv2.COLOR_BGR2GRAY)
# 캐니 에지
edges = cv2.Canny(gray, 30, 70)
# xy 평면을 rho theta 평면 변환
lines = cv2.HoughLines(edges, rho=1, theta=np.pi/180.0, threshold=50)
print('lines.shape=', lines.shape)
lines
# for line in lines:
#     x1, y1, x2, y2 = line[0]
#     cv2.line(src, (x1, y1), (x2, y2), (0, 0, 255), 2)
# cv2.imshow('canny', edges)
# cv2.imshow('src', src)
# cv2.waitKey()
# cv2.destroyAllWindows()
# cv2.waitKey(1)

lines.shape= (12, 1, 2)


array([[[ 3.0000000e+02,  0.0000000e+00]],

       [[ 1.9900000e+02,  0.0000000e+00]],

       [[ 1.9900000e+02,  1.5707964e+00]],

       [[ 3.0000000e+02,  1.5707964e+00]],

       [[ 2.9600000e+02,  1.5882496e+00]],

       [[ 1.9500000e+02,  1.5882496e+00]],

       [[-2.9600000e+02,  3.1241393e+00]],

       [[-1.9500000e+02,  3.1241393e+00]],

       [[ 2.0300000e+02,  1.7453292e-02]],

       [[ 3.0400000e+02,  1.7453292e-02]],

       [[ 2.0300000e+02,  1.5533431e+00]],

       [[ 3.0400000e+02,  1.5533431e+00]]], dtype=float32)

In [192]:
src = cv2.imread('/Users/iseung-won/lena.jpg')
gray = cv2.cvtColor(src, cv2.COLOR_BGR2GRAY)
# 캐니 에지
edges = cv2.Canny(gray, 100, 200)
# xy 평면을 rho theta 평면 변환
lines = cv2.HoughLinesP(edges, rho=5, theta=np.pi/180.0, threshold=30)
print('lines.shape=', lines.shape)
for line in lines:
    x1, y1, x2, y2 = line[0]
    cv2.line(src, (x1, y1), (x2, y2), (0, 0, 255), 2)
cv2.imshow('canny', edges)
cv2.imshow('src', src)
cv2.waitKey()
cv2.destroyAllWindows()
cv2.waitKey(1)
lines

lines.shape= (6397, 1, 4)


array([[[363, 135, 374, 127]],

       [[164, 227, 164, 227]],

       [[147, 493, 147, 493]],

       ...,

       [[247, 229, 247, 229]],

       [[451,  52, 451,  52]],

       [[215, 272, 215, 271]]], dtype=int32)

In [208]:
src = cv2.imread('/Users/iseung-won/circles.jpg')
gray = cv2.cvtColor(src, cv2.COLOR_BGR2GRAY)

edges = cv2.Canny(gray, 100, 200)
lines = cv2.HoughCircles(edges, method = cv2.HOUGH_GRADIENT, dp=1, minDist=50, param2=15)
print(lines)
for line in lines:
    for i in range(len(line)):
        x, y, r = line[i]
        cv2.circle(src, (round(x), round(y)), round(r), (0, 0, 255), 2)

cv2.imshow('canny', edges)
cv2.imshow('src', src)
cv2.waitKey()
cv2.destroyAllWindows()
cv2.waitKey(1)


[[[249.5 250.5  69.6]
  [400.5 170.5  60.6]
  [350.5 400.5  49.6]
  [198.5 245.5  20.2]
  [292.5 224.5  21.7]]]


-1

In [220]:
src = cv2.imread('/Users/iseung-won/circles.jpg')
gray = cv2.cvtColor(src, cv2.COLOR_BGR2GRAY)


lines = cv2.HoughCircles(gray, method = cv2.HOUGH_GRADIENT, dp=1, minDist=50, param2=15)
print(lines)
for line in lines:
    for i in range(len(line)):
        x, y, r = line[i]
        cv2.circle(src, (round(x), round(y)), round(r), (0, 0, 255), 2)

cv2.imshow('canny', edges)
cv2.imshow('src', src)
cv2.waitKey()
cv2.destroyAllWindows()
cv2.waitKey(1)



[[[250.5 251.5  68.5]
  [400.5 168.5  60.6]
  [348.5 399.5  48.5]]]


-1

In [234]:
src = cv2.imread('/Users/iseung-won/lena.jpg')
gray = cv2.cvtColor(src, cv2.COLOR_BGR2GRAY)

edges = cv2.Canny(gray, 50, 200)
lines = cv2.HoughCircles(edges, method = cv2.HOUGH_GRADIENT, dp=1, minDist=200, param2=50)
print(lines)
for line in lines[0, :]:
    x, y, r = line
    cv2.circle(src, (round(x), round(y)), round(r), (0, 0, 255), 2)

cv2.imshow('canny', edges)
cv2.imshow('src', src)
cv2.waitKey()
cv2.destroyAllWindows()
cv2.waitKey(1)

[[[235.5 345.5 148.1]
  [490.5 440.5 329.3]
  [  9.5 227.5 203.3]
  [220.5 136.5  93.1]
  [425.5 227.5  67.4]
  [ 82.5 511.5  70.2]]]


-1

In [232]:
src = cv2.imread('/Users/iseung-won/lena.jpg')
gray = cv2.cvtColor(src, cv2.COLOR_BGR2GRAY)

edges = cv2.Canny(gray, 50, 200)
lines = cv2.HoughCircles(edges, method = cv2.HOUGH_GRADIENT, dp=1, minDist=250, param2=50)
print(lines)
for line in lines[0, :]:
    x, y, r = line
    cv2.circle(src, (round(x), round(y)), round(r), (0, 0, 255), 2)

cv2.imshow('canny', edges)
cv2.imshow('src', src)
cv2.waitKey()
cv2.destroyAllWindows()
cv2.waitKey(1)

[[[235.5 345.5 148.1]
  [490.5 440.5 329.3]
  [  9.5 227.5 203.3]]]


-1

In [231]:
src = cv2.imread('/Users/iseung-won/lena.jpg')
gray = cv2.cvtColor(src, cv2.COLOR_BGR2GRAY)

edges = cv2.Canny(gray, 50, 200)
lines = cv2.HoughCircles(edges, method = cv2.HOUGH_GRADIENT, dp=1, minDist=255, param2=70)
print(lines)
for line in lines[0, :]:
    x, y, r = line
    cv2.circle(src, (round(x), round(y)), round(r), (0, 0, 255), 2)

cv2.imshow('canny', edges)
cv2.imshow('src', src)
cv2.waitKey()
cv2.destroyAllWindows()
cv2.waitKey(1)

[[[234.5 347.5 148.1]]]


-1