In [4]:
import cv2
import random
import numpy as np
kernel = cv2.getStructuringElement(shape=cv2.MORPH_RECT, ksize=(3,3))
kernel

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=uint8)

In [5]:
kernel = np.array( ,np.uint8)

In [46]:
lsta = []
for i in range(5):
    lst2 = []
    lsta.append(lst2)
    for j in range(5):
        lst3 = []
        lst2.append(lst3)
        for k in range(3):
            a = random.randint(-1, 1)
            lst3.append(a)

In [47]:
lsta = []
for i in range(5):
    lst2 = []
    lsta.append(lst2)
    for j in range(5):
        lst3 = []
        lst2.append(lst3)
        for k in range(3):
            a = random.randint(-1, 1)
            lst3.append(a)
lstb = []
for i in range(5):
    lst2 = []
    lstb.append(lst2)
    for j in range(5):
        lst3 = []
        lst2.append(lst3)
        for k in range(3):
            a = random.randint(-1, 1)
            lst3.append(a)

In [51]:
lsta

[[[0, 0, 0], [-1, 1, -1], [0, -1, 1], [-1, 0, 0], [1, 1, 1]],
 [[1, 1, -1], [0, -1, -1], [1, 0, 0], [0, 1, 0], [-1, 0, 0]],
 [[-1, 1, 0], [0, 1, 1], [1, 1, 1], [-1, -1, -1], [0, -1, 0]],
 [[-1, -1, -1], [-1, 0, -1], [-1, 1, -1], [0, -1, 0], [0, 0, 0]],
 [[1, -1, 0], [0, 1, 0], [0, 0, 0], [0, -1, -1], [-1, -1, 1]]]

In [52]:
lstb

[[[-1, 0, 1], [-1, 1, 0], [0, -1, 1], [0, 1, 1], [0, 0, 0]],
 [[0, -1, 1], [-1, -1, -1], [0, 0, 1], [1, 0, 0], [-1, -1, 0]],
 [[0, 0, -1], [1, -1, 1], [1, 0, 0], [1, 1, 1], [1, 0, -1]],
 [[-1, 0, 0], [-1, 1, -1], [0, -1, 1], [0, -1, 1], [0, 0, 1]],
 [[-1, -1, 1], [0, -1, 0], [0, 0, 1], [0, 0, -1], [1, 1, 1]]]

In [57]:
kernel1 = np.array(lsta ,np.uint8)
kernel2 = np.array(lstb ,np.uint8)

In [58]:
kernel1

array([[[  0,   0,   0],
        [255,   1, 255],
        [  0, 255,   1],
        [255,   0,   0],
        [  1,   1,   1]],

       [[  1,   1, 255],
        [  0, 255, 255],
        [  1,   0,   0],
        [  0,   1,   0],
        [255,   0,   0]],

       [[255,   1,   0],
        [  0,   1,   1],
        [  1,   1,   1],
        [255, 255, 255],
        [  0, 255,   0]],

       [[255, 255, 255],
        [255,   0, 255],
        [255,   1, 255],
        [  0, 255,   0],
        [  0,   0,   0]],

       [[  1, 255,   0],
        [  0,   1,   0],
        [  0,   0,   0],
        [  0, 255, 255],
        [255, 255,   1]]], dtype=uint8)

In [50]:
kernel2

array([[[255,   0,   1],
        [255,   1,   0],
        [  0, 255,   1],
        [  0,   1,   1],
        [  0,   0,   0]],

       [[  0, 255,   1],
        [255, 255, 255],
        [  0,   0,   1],
        [  1,   0,   0],
        [255, 255,   0]],

       [[  0,   0, 255],
        [  1, 255,   1],
        [  1,   0,   0],
        [  1,   1,   1],
        [  1,   0, 255]],

       [[255,   0,   0],
        [255,   1, 255],
        [  0, 255,   1],
        [  0, 255,   1],
        [  0,   0,   1]],

       [[255, 255,   1],
        [  0, 255,   0],
        [  0,   0,   1],
        [  0,   0, 255],
        [  1,   1,   1]]], dtype=uint8)

In [60]:
2**16

65536