In [1]:
import numpy as np

In [4]:
test_array = np.array([1,4,5,8], float)

In [5]:
test_array

array([1., 4., 5., 8.])

In [2]:
for i in [1, 2.0, 'text', True]:
    print(type(i))

<class 'int'>
<class 'float'>
<class 'str'>
<class 'bool'>


In [6]:
test_list = [[1,4,5,8], 
             [1,4,5]]
test_list

[[1, 4, 5, 8], [1, 4, 5]]

In [8]:
np.array(test_list, float)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [9]:
test_array = np.array([1,4,5,'8'], float)
print(test_array)

[1. 4. 5. 8.]


In [10]:
print(type(test_array[3]))

<class 'numpy.float64'>


In [11]:
print(test_array.dtype) # 배열 전체의 데이터 타입 반환

float64


In [12]:
print(test_array.shape) # 배열의 구조(shape)를 반환함

(4,)


In [13]:
matrix = [[1,2,5,8], 
          [1,2,5,8], 
          [1,2,5,8]]
np.array(matrix, int).shape

(3, 4)

In [14]:
tensor_rank3 = [
        [[1, 2, 5, 8], 
         [1, 2, 5, 8], 
         [1, 2, 5, 8]],
        [[1, 2, 5, 8], 
         [1, 2, 5, 8], 
         [1, 2, 5, 8]],
        [[1, 2, 5, 8], 
         [1, 2, 5, 8], 
         [1, 2, 5, 8]],
        [[1, 2, 5, 8], 
         [1, 2, 5, 8], 
         [1, 2, 5, 8]]
        ]
np.array(tensor_rank3, int).shape

(4, 3, 4)

In [15]:
tensor_rank3 = [[[1, 2, 5, 8], 
                 [1, 2, 5, 8], 
                 [1, 2, 5, 8]], 
                
                [[1, 2, 5, 8], 
                 [1, 2, 5, 8], 
                 [1, 2, 5, 8]], 
                
                [[1, 2, 5, 8], 
                 [1, 2, 5, 8], 
                 [1, 2, 5, 8]],
                
                [[1, 2, 5, 8], 
                 [1, 2, 5, 8], 
                 [1, 2, 5, 8]]]

np.array(tensor_rank3, int).ndim

3

In [16]:
np.array(tensor_rank3, int).size

48

In [17]:
np.array( [ [1, 2, 3.5], [4, 5, 6.5]], dtype=int)

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
np.array( [ [1, 2, 3.5], [4, 5, 6.5]], dtype=float)

array([[1. , 2. , 3.5],
       [4. , 5. , 6.5]])

In [19]:
np.array( [ [1, 2, 3.5], [4, 5, 6.5]])

array([[1. , 2. , 3.5],
       [4. , 5. , 6.5]])

In [20]:
np.array( [[1, 2, 3.5], [4, 5, 6.5]], dtype=np.float64).itemsize

8

In [21]:
np.array( [[1, 2, 3.5], [4, 5, 6.5]], dtype=np.float32).itemsize

4

In [22]:
np.array( [ [1, 2, 3.5], [4, 5, 6.5]], dtype=int).itemsize

4

In [23]:
np.array( [ [1, 2, 3.5], [4, 5, 6.5]], dtype=float).itemsize

8

In [24]:
x = np.array([[1, 2, 5, 8], 
              [1, 2, 5, 8]])
x.shape

(2, 4)

In [25]:
x.reshape(-1)

array([1, 2, 5, 8, 1, 2, 5, 8])

In [26]:
x = np.array(range(8))
x

array([0, 1, 2, 3, 4, 5, 6, 7])

In [29]:
x = x.reshape(4,2)

In [30]:
x.shape

(4, 2)

In [1]:
x.reshape()

NameError: name 'x' is not defined

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

In [16]:
plt.scatter(np.random.uniform(0, 5, 100))

TypeError: scatter() missing 1 required positional argument: 'y'

In [62]:
a = np.random.normal(0, 2, 100000)
print(np.mean(a))
print(np.var(a))

0.013255832049615283
3.982340559928573


In [66]:
test_array = np.arange(1,13).reshape(3,4)
test_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [68]:
test_array.sum(axis=0)

array([15, 18, 21, 24])

In [69]:
test_array.sum(axis=1)

array([10, 26, 42])

In [70]:
test_array = np.arange(1, 13).reshape(3, 4)
third_order_tensor = np.array([test_array, test_array, test_array])
third_order_tensor

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [72]:
third_order_tensor.sum()

234

In [73]:
third_order_tensor.shape

(3, 3, 4)

In [74]:
third_order_tensor.sum(axis=0)

array([[ 3,  6,  9, 12],
       [15, 18, 21, 24],
       [27, 30, 33, 36]])

In [75]:
third_order_tensor.sum(axis=1)

array([[15, 18, 21, 24],
       [15, 18, 21, 24],
       [15, 18, 21, 24]])

In [76]:
third_order_tensor.sum(axis=2)

array([[10, 26, 42],
       [10, 26, 42],
       [10, 26, 42]])

In [78]:
test_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [81]:
test_array.mean(axis=1)

array([ 2.5,  6.5, 10.5])

In [84]:
test_array.std(axis=0)

array([3.26598632, 3.26598632, 3.26598632, 3.26598632])

In [86]:
np.sqrt(test_array)

array([[1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712],
       [3.        , 3.16227766, 3.31662479, 3.46410162]])

In [87]:
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])
np.vstack((v1, v2))

array([[1, 2, 3],
       [4, 5, 6]])

In [89]:
np.hstack((v1, v2)) # [[1,2,3,4,5,6]]

array([1, 2, 3, 4, 5, 6])

In [92]:
v1 = v1.reshape(-1,1)
v2 = v2.reshape(-1,1)

In [93]:
np.vstack((v1,v2))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [94]:
np.hstack((v1,v2))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [99]:
v1 = np.array([[1,2,3]])
v2 = np.array([[4,5,6]])
np.concatenate((v1,v2), axis=0)

array([[1, 2, 3],
       [4, 5, 6]])

In [100]:
v1 = np.arange(1,5).reshape(2,2)
v1

array([[1, 2],
       [3, 4]])

In [101]:
v2 = [[5], [6]]
v2

[[5], [6]]

In [103]:
np.concatenate((v1, v2), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

In [105]:
x = np.arange(1, 7).reshape(2, 3)

In [106]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [107]:
x + x

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [108]:
x - x

array([[0, 0, 0],
       [0, 0, 0]])

In [109]:
x * x

array([[ 1,  4,  9],
       [16, 25, 36]])

In [110]:
x / x

array([[1., 1., 1.],
       [1., 1., 1.]])

In [111]:
[1,2,3] + [4,5,6]

[1, 2, 3, 4, 5, 6]

In [112]:
x // x

array([[1, 1, 1],
       [1, 1, 1]], dtype=int32)

In [113]:
x % x

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [114]:
x ** x

array([[    1,     4,    27],
       [  256,  3125, 46656]], dtype=int32)

dot product

In [2]:
import numpy as np

x1 = np.arange(1, 7).reshape(2, 3)
x2 = np.arange(1, 7).reshape(3, 2)

In [3]:
x1 # 2 x 3

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
x2 # 3 x 2 > 2 x 2

array([[1, 2],
       [3, 4],
       [5, 6]])

In [5]:
x1.dot(x2)

array([[22, 28],
       [49, 64]])

In [6]:
x1 = np.arange(1, 11).reshape(2, 5) # 2 x 5
x2 = np.arange(1, 16).reshape(5, 3) # 5 x 3 dot product > 2 x 3

In [7]:
x1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [8]:
x2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [9]:
x1.dot(x2)

array([[135, 150, 165],
       [310, 350, 390]])

In [10]:
x2.dot(x1)

ValueError: shapes (5,3) and (2,5) not aligned: 3 (dim 1) != 2 (dim 0)

In [11]:
x1 = np.arange(1, 10).reshape(3, 3)
x1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
x2 = x1 + 3

In [14]:
x2 - x1

array([[3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])

In [15]:
x1 - 2

array([[-1,  0,  1],
       [ 2,  3,  4],
       [ 5,  6,  7]])

In [16]:
x1 * 2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [17]:
x1 / 2

array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ],
       [3.5, 4. , 4.5]])

In [18]:
x1 ** 2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]], dtype=int32)

In [19]:
x1 // 2

array([[0, 1, 1],
       [2, 2, 3],
       [3, 4, 4]], dtype=int32)

In [20]:
x1 % 2

array([[1, 0, 1],
       [0, 1, 0],
       [1, 0, 1]], dtype=int32)

In [21]:
x1 + 3.0

array([[ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.]])

In [22]:
x1 + 'a'

UFuncTypeError: ufunc 'add' did not contain a loop with signature matching types (dtype('int32'), dtype('<U1')) -> None

In [23]:
x1 + [1]

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [24]:
x1 + [1, 2]

ValueError: operands could not be broadcast together with shapes (3,3) (2,) 

In [25]:
x1 = np.arange(1, 13).reshape(4, 3)  # 4 x 3
x2 = np.arange(10, 40, 10) # 1 x 3

In [26]:
x1 # 4x3

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [27]:
x2 # 1x3

array([10, 20, 30])

In [28]:
x1 + x2

array([[11, 22, 33],
       [14, 25, 36],
       [17, 28, 39],
       [20, 31, 42]])

In [32]:
def sclar_vector_product(scalar, vector):
    result = []
    for value in vector:
        result.append(scalar * value)
    return result

iteration_max = 100000000
vector = list(range(iteration_max))
scalar = 2

In [33]:
%timeit sclar_vector_product(scalar, vector)

9.99 s ± 324 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [34]:
%timeit [scalar * value for value in range(iteration_max)]

9.59 s ± 475 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [37]:
%timeit np.arange(iteration_max) * scalar

353 ms ± 80 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


비교 연산

In [53]:
x = np.array([4,3,2,6,8,5])
x >= 3

array([ True,  True, False,  True,  True,  True])

In [43]:
x != 3

array([ True, False,  True,  True,  True,  True])

In [44]:
x = np.array([1,3,0])
y = np.array([2,1,7])
x > y

array([False,  True, False])

In [45]:
x < y

array([ True, False,  True])

In [46]:
x >= y

array([False,  True, False])

In [47]:
x <= y

array([ True, False,  True])

In [48]:
x == y

array([False, False, False])

In [49]:
x != y

array([ True,  True,  True])

In [50]:
y1 = np.array([2,1,7,0])

In [51]:
x > y1

ValueError: operands could not be broadcast together with shapes (3,) (4,) 

In [56]:
x > 3

array([ True, False, False,  True,  True,  True])

In [55]:
(x > 3).all()

False

In [57]:
(x > 3).any()

True

In [60]:
(x < 10).any()

True

인덱스 반환 함수 where

In [61]:
x

array([4, 3, 2, 6, 8, 5])

In [62]:
np.where(x>5)

(array([3, 4], dtype=int64),)

In [63]:
?np.where

In [66]:
np.where(x>5, 0, 1)

array([1, 1, 1, 0, 0, 1])

정렬된 값의 인덱스 반환 함수들

In [67]:
np.argsort(x)

array([2, 1, 0, 5, 3, 4], dtype=int64)

In [68]:
np.argmax(x)

4

In [69]:
np.argmin(x)

2

In [70]:
x

array([4, 3, 2, 6, 8, 5])

In [79]:
x[[True, False, False,  True,  True]]

IndexError: boolean index did not match indexed array along dimension 0; dimension is 6 but corresponding boolean dimension is 5

In [72]:
x>3

array([ True, False, False,  True,  True,  True])

In [75]:
x.shape

(6,)

In [76]:
(x > 3).shape

(6,)

Fancy index

In [88]:
x = np.array([4,6,7,3,2])
cond = np.array([1,2,0,2,2,2,3,0], int)

In [89]:
x[cond]

array([6, 7, 4, 7, 7, 7, 3, 4])

In [90]:
x[[1,2,0,2,2,2,3,0]]

array([6, 7, 4, 7, 7, 7, 3, 4])

In [91]:
x.take([1,2,0,2,2,2,3,0])

array([6, 7, 4, 7, 7, 7, 3, 4])

In [92]:
x = np.array([[1,4], [9,16]], int)
a = np.array([0, 1, 1, 1, 0, 0], int)
b = np.array([0, 0, 0, 1, 1, 1], int)
x[a,b]

array([ 1,  9,  9, 16,  4,  4])

In [93]:
x

array([[ 1,  4],
       [ 9, 16]])

In [94]:
x[a]

array([[ 1,  4],
       [ 9, 16],
       [ 9, 16],
       [ 9, 16],
       [ 1,  4],
       [ 1,  4]])

In [95]:
x[b]

array([[ 1,  4],
       [ 1,  4],
       [ 1,  4],
       [ 9, 16],
       [ 9, 16],
       [ 9, 16]])

In [96]:
x[a, b]

array([ 1,  9,  9, 16,  4,  4])