In [2]:
import numpy as np

In [23]:
x_1 = np.arange(1,11).reshape(2,5)
x_2 = np.arange(1,16).reshape(5,3)
x_1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [24]:
x_2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [25]:
x_1.dot(x_2)

array([[135, 150, 165],
       [310, 350, 390]])

In [19]:
x_2.dot(x_1)

ValueError: shapes (5,3) and (2,5) not aligned: 3 (dim 1) != 2 (dim 0)

In [27]:
x = np.arange(1,10).reshape(3,3)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [28]:
x+10

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [30]:
x-2

array([[-1,  0,  1],
       [ 2,  3,  4],
       [ 5,  6,  7]])

In [40]:
x*3.0

array([[ 3.,  6.,  9.],
       [12., 15., 18.],
       [21., 24., 27.]])

In [32]:
x/4

array([[0.25, 0.5 , 0.75],
       [1.  , 1.25, 1.5 ],
       [1.75, 2.  , 2.25]])

In [33]:
x**2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [39]:
x%2

array([[1, 0, 1],
       [0, 1, 0],
       [1, 0, 1]])

In [41]:
x + 'a'

UFuncTypeError: ufunc 'add' did not contain a loop with signature matching types (dtype('int64'), dtype('<U1')) -> None

In [42]:
x + [1]

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [43]:
x + [1,2]

ValueError: operands could not be broadcast together with shapes (3,3) (2,) 

In [45]:
x = np.arange(1,13).reshape(4,3)
x

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [46]:
h = np.arange(10,40,10)
h

array([10, 20, 30])

In [47]:
x + h

array([[11, 22, 33],
       [14, 25, 36],
       [17, 28, 39],
       [20, 31, 42]])

In [48]:
x * h

array([[ 10,  40,  90],
       [ 40, 100, 180],
       [ 70, 160, 270],
       [100, 220, 360]])

In [50]:
import time

In [49]:
def sclar_vector_product(scalar, vector):
    result = []
    for value in vector:
        result.append(scalar * value)
    return result

iternation_max = 100000000

vector = list(range(iternation_max))
scalar = 2

In [51]:
# for 문을 이용한 성능
%timeit sclar_vector_product(scalar, vector)

6.65 s ± 239 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [52]:
#리스트 컴프리헨션을 이용한 성능
%timeit [scalar * value for value in range(iternation_max)]

6 s ± 34.2 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [53]:
#넘파이를 이용한 성능
%timeit np.arange(iternation_max) * scalar

200 ms ± 3.67 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [55]:
x = np.array([4,3,2,6,8,5])
x > 3

array([ True, False, False,  True,  True,  True])

In [57]:
x<3

array([False, False,  True, False, False, False])

In [58]:
x==3

array([False,  True, False, False, False, False])

In [59]:
# 요소별 비교 연산
#  - 두 개의 배열 간 배열의 구조(shape	)가 동일한 경우
#  - 같은 위치에 있는 요소들끼리 비교 연산
#  - [1>2,3>1,0>7]과 같이 연산이 실시 된 후 이를 반환

x = np.array([1,3,0])
y = np.array([2,1,7])
x>y

array([False,  True, False])

In [60]:
x<=y

array([ True, False,  True])

In [61]:
x!=y

array([ True,  True,  True])

In [62]:
y2 = np.array([2,1,7,6])

In [63]:
x>y2

ValueError: operands could not be broadcast together with shapes (3,) (4,) 

In [65]:
x = np.array([4,6,7,3,2])
x>3

array([ True,  True,  True, False, False])

In [66]:
(x>3).all()

False

In [67]:
(x>3).any()

True

In [68]:
(x<10).any()

True

In [69]:
(x<10).all()

True

In [70]:
(x>10).any()

False

In [71]:
x>5

array([False,  True,  True, False, False])

In [72]:
# 인덱스를 표시

np.where(x>5)

(array([1, 2]),)

In [76]:
#  True/False 대신 참/거짓인 경우의 값을 지정할 수 있음 참 = 10, 거짓 = 20

x = np.array([4,5,6,3,2])
np.where(x>5,2,1)

array([1, 1, 2, 1, 1])

In [81]:
#  - argwort : 배열 내 값들을 작은 순서대로 인덱스를 반환
#  - argmax : 배열 내 값들 중 가장 큰 값의 인덱스를 반환
#  - argmin : 배열 내 값들 중 가장 작은 값의 인덱스를 반환

x = np.array([3,5,6,8,9,4])
np.argsort(x)

array([0, 5, 1, 2, 3, 4])

In [82]:
np.argmax(x)

4

In [83]:
np.argmin(x)

0

In [84]:
x = np.array([4,6,7,3,2])
x>3

array([ True,  True,  True, False, False])

In [85]:
cond = x>3
x[cond]

array([4, 6, 7])

In [88]:
x[[ True,  True,  True, False, False]]

array([4, 6, 7])

In [89]:
x[[ True,  True,  True, False]]

IndexError: boolean index did not match indexed array along dimension 0; dimension is 5 but corresponding boolean dimension is 4

In [97]:
x.shape

(2, 2)

In [98]:
cond.shape

(6,)

In [100]:
x = np.array([4,6,7,3,2])
cond = np.array([1,2,0,3,4,2,1,1,2])
x[cond]

array([6, 7, 4, 3, 2, 7, 6, 6, 7])

In [93]:
x.take(cond)

array([4, 9, 1, 9, 9, 9])

In [92]:
x = np.array([[1,4],[9,16]],int)
a = np.array([0,1,1,1,0,0], int)
b = np.array([0,0,0,1,1,1],int)
x[a,b]

array([ 1,  9,  9, 16,  4,  4])

In [94]:
x

array([[ 1,  4],
       [ 9, 16]])

In [95]:
x[a]

array([[ 1,  4],
       [ 9, 16],
       [ 9, 16],
       [ 9, 16],
       [ 1,  4],
       [ 1,  4]])

In [96]:
x[b]

array([[ 1,  4],
       [ 1,  4],
       [ 1,  4],
       [ 9, 16],
       [ 9, 16],
       [ 9, 16]])

In [101]:
import pandas as pd

In [102]:
list_data = [1,2,3,4,5]
example_obj = pd.Series(list_data)
example_obj

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [104]:
list_data = [1,2,3,4,5]
list_name = ["a", "b", "c", "d", "e"]
example_obj = pd.Series(data = list_data, index = list_name)
example_obj

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [110]:
dict_data_1 = {'a':1, "b":2, "c":3, 'd':4, "e":5}
indexes = ["a",'b',"c","d","e","f", "g", "h"]
series_obj_1 = pd.Series(dict_data_1)
series_obj_1

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [111]:
dict_data_1 = {'a':1, "b":2, "c":3, 'd':4, "e":5}
indexes = ["a",'b',"c","d","e","f", "g", "h"]
series_obj_1 = pd.Series(dict_data_1, index=indexes)
series_obj_1

a    1.0
b    2.0
c    3.0
d    4.0
e    5.0
f    NaN
g    NaN
h    NaN
dtype: float64

In [113]:
dict_data = {'a':1, "b":2, "c":3, 'd':4, "e":5}
example_obj = pd.Series(dict_data, dtype = np.float32)
example_obj

a    1.0
b    2.0
c    3.0
d    4.0
e    5.0
dtype: float32

In [122]:
dict_data = {'a':1, "b":2, "c":3, 'd':4, "e":5}
example_obj3 = pd.Series(dict_data, dtype = np.float32, name = "example_data")
example_obj3

a    1.0
b    2.0
c    3.0
d    4.0
e    5.0
Name: example_data, dtype: float32

In [117]:
example_obj.values

array([1., 2., 3., 4., 5.], dtype=float32)

In [118]:
example_obj.index

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [119]:
example_obj.values.dtype

dtype('float32')

In [120]:
type(example_obj.values)

numpy.ndarray

In [123]:
example_obj3.name = "name"
example_obj3.index.name = "d"
example_obj3

d
a    1.0
b    2.0
c    3.0
d    4.0
e    5.0
Name: name, dtype: float32

In [124]:
series_obj_1[0]

1.0

In [125]:
series_obj_1["b"]

2.0

In [132]:
series_obj_1[["c","e"]]

c    3.0
e    5.0
dtype: float64

In [133]:
series_obj_1[[2,4]]

c    3.0
e    5.0
dtype: float64

In [130]:
series_obj_1["c":"e":2]

c    3.0
e    5.0
dtype: float64

In [128]:
series_obj_1["b":"d"]

b    2.0
c    3.0
d    4.0
dtype: float64

In [134]:
series_obj_1[1:4]

b    2.0
c    3.0
d    4.0
dtype: float64

In [142]:
student = ["준서", "예은"]
datas = {"나이":[15,17],"성별":["남","여"],"학교" : ["덕영중", "수리중"]}
df = pd.DataFrame(datas, index=student)

In [143]:
df

나이 성별   학교
준서  15  남  덕영중
예은  17  여  수리중

In [146]:
pd.DataFrame([[15, '남', '덕영중'],
             [17, '여', '수리중']], 
             columns=['나이', '성별', '학교'],
             index = ['준서', '예은'])

나이 성별   학교
준서  15  남  덕영중
예은  17  여  수리중

In [147]:
pd.DataFrame([[15,17],
             ['남', '여'],
             ['덕영중', '수리중']
             ])

0    1
0   15   17
1    남    여
2  덕영중  수리중

In [159]:
raw_data = {'first_name': ['Jason', 'Molly', 'Tina', 'Jake', 'Amy'],
            'last_name': ['Miller', 'Jacobson', 'Ali', 'Milner', 'Cooze'],
            'age': [42, 52, 36, 24, 73],
            'city': ['San Francisco', 'Baltimore', 'Miami', 'Douglas', 'Boston']}

In [162]:
df=pd.DataFrame(raw_data)
df

first_name last_name  age           city
0      Jason    Miller   42  San Francisco
1      Molly  Jacobson   52      Baltimore
2       Tina       Ali   36          Miami
3       Jake    Milner   24        Douglas
4        Amy     Cooze   73         Boston

In [165]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [166]:
df.columns

Index(['first_name', 'last_name', 'age', 'city'], dtype='object')

In [170]:
df.columns[1:4]

Index(['last_name', 'age', 'city'], dtype='object')

In [174]:
df1=pd.DataFrame(raw_data, columns=["age", "city"])

In [175]:
df1

age           city
0   42  San Francisco
1   52      Baltimore
2   36          Miami
3   24        Douglas
4   73         Boston

In [176]:
pd.DataFrame(raw_data, columns=["first_name", 'last_name', 'age', 'city', 'debt'])

first_name last_name  age           city debt
0      Jason    Miller   42  San Francisco  NaN
1      Molly  Jacobson   52      Baltimore  NaN
2       Tina       Ali   36          Miami  NaN
3       Jake    Milner   24        Douglas  NaN
4        Amy     Cooze   73         Boston  NaN

In [181]:
df = pd.DataFrame(raw_data, columns=["first_name", 'last_name', 'age', 'city'])
df.index = ['student1', 'student2', 'student3', 'student4', 'student5']
df.columns = ['이름', '성', '나이', '지역']
print(df) #데이터프레임

             이름         성  나이             지역
student1  Jason    Miller  42  San Francisco
student2  Molly  Jacobson  52      Baltimore
student3   Tina       Ali  36          Miami
student4   Jake    Milner  24        Douglas
student5    Amy     Cooze  73         Boston


In [186]:
print(df.index) #행 인덱스

Index(['student1', 'student2', 'student3', 'student4', 'student5'], dtype='object')


In [184]:
print(df.columns)#열 이름

Index(['이름', '성', '나이', '지역'], dtype='object')


In [187]:
df.columns = ['이름', '성']

ValueError: Length mismatch: Expected axis has 4 elements, new values have 2 elements

In [194]:
df.rename(columns={'나이':'연령', '지역':'도시', '성':'ln', '이름':'fn'}, inplace=True)

In [189]:
df.rename(index={'student1':'학생1', 'student2':'학생2'}, inplace=True)

In [190]:
df

fn        ln  연령             도시
학생1       Jason    Miller  42  San Francisco
학생2       Molly  Jacobson  52      Baltimore
student3   Tina       Ali  36          Miami
student4   Jake    Milner  24        Douglas
student5    Amy     Cooze  73         Boston

fn        ln  연령             도시
학생1       Jason    Miller  42  San Francisco
학생2       Molly  Jacobson  52      Baltimore
student3   Tina       Ali  36          Miami
student4   Jake    Milner  24        Douglas
student5    Amy     Cooze  73         Boston

In [195]:
df.rename(columns={'나이':'gg', '지역':'ff', '성':'ee', '이름':'rr'}, inplace=False)

fn        ln  연령             도시
학생1       Jason    Miller  42  San Francisco
학생2       Molly  Jacobson  52      Baltimore
student3   Tina       Ali  36          Miami
student4   Jake    Milner  24        Douglas
student5    Amy     Cooze  73         Boston

In [196]:
df.rename(columns={'나이':'gg', '지역':'ff', '성':'ee', '이름':'rr'})

fn        ln  연령             도시
학생1       Jason    Miller  42  San Francisco
학생2       Molly  Jacobson  52      Baltimore
student3   Tina       Ali  36          Miami
student4   Jake    Milner  24        Douglas
student5    Amy     Cooze  73         Boston

In [197]:
df.rename({'연령':'age'}, axis=1)

fn        ln  age             도시
학생1       Jason    Miller   42  San Francisco
학생2       Molly  Jacobson   52      Baltimore
student3   Tina       Ali   36          Miami
student4   Jake    Milner   24        Douglas
student5    Amy     Cooze   73         Boston

In [198]:
df.rename({'연령':'age'}, axis=0)

fn        ln  연령             도시
학생1       Jason    Miller  42  San Francisco
학생2       Molly  Jacobson  52      Baltimore
student3   Tina       Ali  36          Miami
student4   Jake    Milner  24        Douglas
student5    Amy     Cooze  73         Boston

In [201]:
df.rename({'학생1':'s2'}, axis=1)

fn        ln  연령             도시
학생1       Jason    Miller  42  San Francisco
학생2       Molly  Jacobson  52      Baltimore
student3   Tina       Ali  36          Miami
student4   Jake    Milner  24        Douglas
student5    Amy     Cooze  73         Boston

In [206]:
df=pd.read_excel('/Users/iseung-won/excel-comp-data.xlsx')

In [207]:
df

account                              name  \
0    211829        Kerluke, Koepp and Hilpert   
1    320563                    Walter-Trantow   
2    648336        Bashirian, Kunde and Price   
3    109996       D'Amore, Gleichner and Bode   
4    121213                     Bauch-Goldner   
5    132971  Williamson, Schumm and Hettinger   
6    145068                        Casper LLC   
7    205217                  Kovacek-Johnston   
8    209744                    Champlin-Morar   
9    212303                    Gerhold-Maggio   
10   214098       Goodwin, Homenick and Jerde   
11   231907                        Hahn-Moore   
12   242368      Frami, Anderson and Donnelly   
13   268755                       Walsh-Haley   
14   273274                     McDermott PLC   

                                  street               city          state  \
0                     34456 Sean Highway         New Jaycob          Texas   
1                      1311 Alvis Tunnel      Port Khadijah  NorthCarolina   
2   62184 Schamberger Underpass Apt. 231     New Lilianland           Iowa   
3            155 Fadel Crescent Apt. 144         Hyattburgh          Maine   
4                    7274 Marissa Common    Shanahanchester     California   
5                   89403 Casimer Spring       Jeremieburgh       Arkansas   
6           340 Consuela Bridge Apt. 400  Lake Gabriellaton     Mississipi   
7           91971 Cronin Vista Suite 601         Deronville    RhodeIsland   
8                       26739 Grant Lock    Lake Juliannton   Pennsylvania   
9              366 Maggio Grove Apt. 998          North Ras          Idaho   
10             649 Cierra Forks Apt. 078           Rosaberg       Tenessee   
11              18115 Olivine Throughway      Norbertomouth    NorthDakota   
12                       182 Bertie Road        East Davian           Iowa   
13                  2624 Beatty Parkways       Goodwinmouth    RhodeIsland   
14                 8917 Bergstrom Meadow    Kathryneborough       Delaware   

    postal-code     Jan     Feb     Mar  
0         28752   10000   62000   35000  
1         38365   95000   45000   35000  
2         76517   91000  120000   35000  
3         46021   45000  120000   10000  
4         49681  162000  120000   35000  
5         62785  150000  120000   35000  
6         18008   62000  120000   70000  
7         53461  145000   95000   35000  
8         64415   70000   95000   35000  
9         46308   70000  120000   35000  
10        47743   45000  120000   55000  
11        31415  150000   10000  162000  
12        72686  162000  120000   35000  
13        31919   55000  120000   35000  
14        27933  150000  120000   70000

In [208]:
df.head()

account                         name                                street  \
0   211829   Kerluke, Koepp and Hilpert                    34456 Sean Highway   
1   320563               Walter-Trantow                     1311 Alvis Tunnel   
2   648336   Bashirian, Kunde and Price  62184 Schamberger Underpass Apt. 231   
3   109996  D'Amore, Gleichner and Bode           155 Fadel Crescent Apt. 144   
4   121213                Bauch-Goldner                   7274 Marissa Common   

              city          state  postal-code     Jan     Feb    Mar  
0       New Jaycob          Texas        28752   10000   62000  35000  
1    Port Khadijah  NorthCarolina        38365   95000   45000  35000  
2   New Lilianland           Iowa        76517   91000  120000  35000  
3       Hyattburgh          Maine        46021   45000  120000  10000  
4  Shanahanchester     California        49681  162000  120000  35000

In [221]:
df.head(1)

account                        name              street        city  state  \
0   211829  Kerluke, Koepp and Hilpert  34456 Sean Highway  New Jaycob  Texas   

   postal-code    Jan    Feb    Mar  
0        28752  10000  62000  35000

In [213]:
df.tail()

account                          name                     street  \
10   214098   Goodwin, Homenick and Jerde  649 Cierra Forks Apt. 078   
11   231907                    Hahn-Moore   18115 Olivine Throughway   
12   242368  Frami, Anderson and Donnelly            182 Bertie Road   
13   268755                   Walsh-Haley       2624 Beatty Parkways   
14   273274                 McDermott PLC      8917 Bergstrom Meadow   

               city        state  postal-code     Jan     Feb     Mar  
10         Rosaberg     Tenessee        47743   45000  120000   55000  
11    Norbertomouth  NorthDakota        31415  150000   10000  162000  
12      East Davian         Iowa        72686  162000  120000   35000  
13     Goodwinmouth  RhodeIsland        31919   55000  120000   35000  
14  Kathryneborough     Delaware        27933  150000  120000   70000

In [211]:
df.tail(2)

account           name                 street             city  \
13   268755    Walsh-Haley   2624 Beatty Parkways     Goodwinmouth   
14   273274  McDermott PLC  8917 Bergstrom Meadow  Kathryneborough   

          state  postal-code     Jan     Feb    Mar  
13  RhodeIsland        31919   55000  120000  35000  
14     Delaware        27933  150000  120000  70000

In [214]:
df['account'].head(3)

0    211829
1    320563
2    648336
Name: account, dtype: int64

In [215]:
df[['account']].head(3)

account
0   211829
1   320563
2   648336

In [217]:
df[['account', 'street', 'state']].head(3)

account                                street          state
0   211829                    34456 Sean Highway          Texas
1   320563                     1311 Alvis Tunnel  NorthCarolina
2   648336  62184 Schamberger Underpass Apt. 231           Iowa

In [218]:
df['account', 'street', 'state'].head(3)

KeyError: ('account', 'street', 'state')

In [220]:
df.account # == df['account']

0     211829
1     320563
2     648336
3     109996
4     121213
5     132971
6     145068
7     205217
8     209744
9     212303
10    214098
11    231907
12    242368
13    268755
14    273274
Name: account, dtype: int64

In [223]:
df['account']

0     211829
1     320563
2     648336
3     109996
4     121213
5     132971
6     145068
7     205217
8     209744
9     212303
10    214098
11    231907
12    242368
13    268755
14    273274
Name: account, dtype: int64

In [222]:
df[['account', 'street', 'state']]

account                                street          state
0    211829                    34456 Sean Highway          Texas
1    320563                     1311 Alvis Tunnel  NorthCarolina
2    648336  62184 Schamberger Underpass Apt. 231           Iowa
3    109996           155 Fadel Crescent Apt. 144          Maine
4    121213                   7274 Marissa Common     California
5    132971                  89403 Casimer Spring       Arkansas
6    145068          340 Consuela Bridge Apt. 400     Mississipi
7    205217          91971 Cronin Vista Suite 601    RhodeIsland
8    209744                      26739 Grant Lock   Pennsylvania
9    212303             366 Maggio Grove Apt. 998          Idaho
10   214098             649 Cierra Forks Apt. 078       Tenessee
11   231907              18115 Olivine Throughway    NorthDakota
12   242368                       182 Bertie Road           Iowa
13   268755                  2624 Beatty Parkways    RhodeIsland
14   273274                 8917 Bergstrom Meadow       Delaware