In [1]:
import numpy as np

In [4]:
 # 매개 변수  1: 배열정보
 # 매개 변수  2: 

NameError: name 'a' is not defined

In [ ]:
test_array = np.array([1,4,5,8], float) # 배열에 들어가는 요소들의 타입은 모두 같아야 함 여기서는 float로 설정

In [5]:
test_array

array([1., 4., 5., 8.])

In [11]:
type(test_array[3])

numpy.float64

In [6]:
for i in [1,2.0, 'txt', True]: # 그냥 list는 타입이 같을 필요가 없음
    print(type(i))

<class 'int'>
<class 'float'>
<class 'str'>
<class 'bool'>


In [10]:
test_list = [[1,4,5,8],[1,4,5]]
test_list

[[1, 4, 5, 8], [1, 4, 5]]

In [8]:
np.array(test_list, float) #value error

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [9]:
# 동적 타이핑을 지원하지 않음
    # - 하나의 데이터 타입만 사용
# 데이터를 메모리에 연속적으로 나열
    # - 각 값 메모리 크기가 동일
    # - 검색이나 연산 속도가 리스트에 비해 훨씬 빠름

In [16]:
test_array = np.array([1,4,5,"8"], float)
print(test_array)

[1. 4. 5. 8.]


In [13]:
print(type(test_array[3])) # 실수형으로 자동 형 변환 실시

<class 'numpy.float64'>


In [14]:
print(test_array.dtype) #배열 전체의 데이터 타입 변환

float64


In [15]:
print(test_array.shape) #배열의 구조(shape)를 변황함

(4,)


In [22]:
matrix = [[1,2,5,8], [1,2,5,8], [1,2,5,8]]
np.array(matrix, int).shape

(3, 4)

In [31]:
np.array(matrix, int).ndim

2

In [28]:
tensor_rank3 = [
    [[1,2,5,8],[1,2,5,8],[1,2,5,8]],
    [[1,2,5,8],[1,2,5,8],[1,2,5,8]],
    [[1,2,5,8],[1,2,5,8],[1,2,5,8]],
    [[1,2,5,8],[1,2,5,8],[1,2,5,8]]
    ]
np.array(tensor_rank3, int).shape

(4, 3, 4)

In [29]:
np.array(tensor_rank3, int).ndim

3

In [30]:
np.array(tensor_rank3, int).size

48

In [33]:
np.array([[1,2,3.5],[4,5,6.5]], dtype=int)

array([[1, 2, 3],
       [4, 5, 6]])

In [34]:
np.array([[1,2,3.5],[4,5,6.5]], dtype=float)

array([[1. , 2. , 3.5],
       [4. , 5. , 6.5]])

In [37]:
import sys
np.array([[1,2,3.5],[4,5,6.5]], dtype=np.float32).itemsize

4

In [38]:
import sys
np.array([[1,2,3.5],[4,5,6.5]], dtype=np.float64).itemsize

8

In [39]:
np.array([[1,2,3.5],[4,5,6.5]], dtype=float).itemsize

8

In [42]:
np.array([[1,2,3.5],[4,5,6.5]], int).itemsize

8

In [71]:
x = np.array([[1,2,5,8],[1,2,5,8]])
x.shape

(2, 4)

In [72]:
x.reshape(-1,)

array([1, 2, 5, 8, 1, 2, 5, 8])

In [95]:
x.reshape(-1,+1+1)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [74]:
x=np.array(range(8))
x

array([0, 1, 2, 3, 4, 5, 6, 7])

In [88]:
x.reshape(-1)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [93]:
x.reshape(2,4)

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [105]:
x.reshape(4,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [107]:
x.reshape(4,-1)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [97]:
x.reshape(2,-1)

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [110]:
x.reshape(2,2,-1)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [119]:
x.reshape(2,2,2,1)

array([[[[0],
         [1]],

        [[2],
         [3]]],


       [[[4],
         [5]],

        [[6],
         [7]]]])

In [114]:
x1 = np.array(range(8)).reshape(2,2,2)
x1

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [115]:
x.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7])

In [121]:
x.shape

(4, 2)

In [122]:
x = np.array([[1,2,3],[4,5,6]], int)
x

array([[1, 2, 3],
       [4, 5, 6]])

In [135]:
x[0][0]

1

In [124]:
x[0,2]

3

In [125]:
x[0,1] =100
x

array([[  1, 100,   3],
       [  4,   5,   6]])

In [126]:
tensor_rank3[0]

[[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]]

In [136]:
x = np.array([[1,2,3,4,5],[6,7,8,9,10]], int)
x[:,2:]# 전체 행의 2열 이상

array([[ 3,  4,  5],
       [ 8,  9, 10]])

In [137]:
x[1,1:3] # 1행의 1열~2열

array([7, 8])

In [145]:
x[1:3]  # 1행~2행 전체

array([[ 6,  7,  8,  9, 10]])

In [141]:
x[1:3,1:4]

array([[7, 8, 9]])

In [142]:
x[1:3][1:4]

array([], shape=(0, 5), dtype=int64)

In [146]:
x = np.array(range(15), int).reshape(3,-1)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [166]:
x[:,::2]

array([[ 0,  2,  4],
       [ 5,  7,  9],
       [10, 12, 14]])

In [167]:
x[::2,::3]

array([[ 0,  3],
       [10, 13]])

In [171]:
np.array(range(10))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [168]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [169]:
np.arange(-5,5)

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4])

In [170]:
np.arange(0,5,0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [172]:
np.array(range(0,5,0.5))

TypeError: 'float' object cannot be interpreted as an integer

In [174]:
np.ones(shape=(5,2), dtype=np.int8)

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]], dtype=int8)

In [175]:
np.zeros(shape=(2,2), dtype=np.float32)

array([[0., 0.],
       [0., 0.]], dtype=float32)

In [199]:
np.empty(shape=(2,4), dtype=np.float32)

array([[9.1835e-41, 0.0000e+00, 0.0000e+00, 0.0000e+00],
       [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]], dtype=float32)

In [186]:
np.empty(shape=(2,4), dtype=np.float32)

array([[9.1835e-41, 0.0000e+00, 0.0000e+00, 0.0000e+00],
       [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]], dtype=float32)

In [190]:
x = np.array(range(12)).reshape(3,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [191]:
np.ones_like(x)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [192]:
np.zeros_like(x)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [200]:
np.empty_like(x)

array([[                  0,                2043,                   0,
                          0],
       [                  0, 3760061921801430379, 3270006062911599415,
        3559308449243739184],
       [3975896960386346288, 3977579392774267749, 8386112019186136422,
                      29557]])

In [201]:
# identity 함수 : 단위행렬(i행렬)을 생성 
    # 매개 변수 n으로 n x n단위 행렬을 생성

In [207]:
np.identity(n=(3),dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [210]:
np.identity(n=(4),dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [ ]:
# eye함수 : 시작점과 행렬 크기를 지정 해서단위행렬 생성
    #N은 행이 갯수, M은 열의 갯수, k는 1이 시작 하는 위치

In [212]:
np.eye(N=3,M=5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [217]:
np.eye(N=3,M=5,k=2)

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [218]:
np.eye(3,5,2)

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [219]:
# diag 함수 : 행렬의 대각성분 값을 추출

In [224]:
np.diag(np.array(range(9)).reshape(3,3),k=0)

array([0, 4, 8])

In [225]:
np.diag(np.array(range(9)).reshape(3,3),k=1)

array([1, 5])

In [226]:
matrix = np.arange(9).reshape(3,3)
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [229]:
np.diag(matrix)

array([0, 4, 8])

In [230]:
np.diag(matrix, k=1)

array([1, 5])

In [231]:
# uniform 함수 : 균등분포 함수
# 'np.random.uniform(시작값, 끝값, 데이터개수)'

In [237]:
np.random.uniform(low = 0, high = 5, size = 10)

array([3.04265543, 2.23136483, 4.38190727, 0.23999495, 3.179586  ,
       4.44281793, 1.39956383, 2.8549868 , 1.91323257, 4.83173376])

In [238]:
np.sum(np.random.uniform(low = 0, high = 5, size = 10))

24.5224978963161

In [240]:
np.mean(np.random.uniform(low = 0, high = 5, size = 10))

2.4467763421326314

In [241]:
# normal 함수 : 정규분포 함수
 # 'np.random.normal(평균값,분산, 데이터개수)'

In [280]:
a=np.random.normal(0,2,100000)
print(np.mean(a))
print(np.std(a))
print(np.var(a))

0.0009487026670392609
2.001184128531259
4.004737916285413


In [279]:
np.sum(np.random.normal(0,2,10))

-2.2182382189873646

In [244]:
np.mean(np.random.normal(0,2,10))

-0.718537250323529

In [245]:
np.var(np.random.normal(0,2,10))

2.2139516213989934

In [281]:
test_array = np.arange(1,11)
test_array.sum()

55

In [284]:
test_array1 = np.arange(1,13).reshape(3,4)

In [287]:
print(test_array1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [289]:
test_array1.sum(axis=None)

78

In [290]:
test_array1.sum(axis=0)

array([15, 18, 21, 24])

In [291]:
test_array1.sum(axis=1)

array([10, 26, 42])

In [285]:
print(np.sum(test_array1, axis=0))

[15 18 21 24]


In [286]:
print(np.sum(test_array1, axis=1))

[10 26 42]


In [292]:
test_array2 = np.arange(1,13).reshape(3,4)
third_order_tensor = np.array([test_array2,test_array2,test_array2])
third_order_tensor

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [293]:
third_order_tensor.sum(axis=0)

array([[ 3,  6,  9, 12],
       [15, 18, 21, 24],
       [27, 30, 33, 36]])

In [294]:
third_order_tensor.sum(axis=1)

array([[15, 18, 21, 24],
       [15, 18, 21, 24],
       [15, 18, 21, 24]])

In [295]:
third_order_tensor.sum(axis=2)

array([[10, 26, 42],
       [10, 26, 42],
       [10, 26, 42]])

In [296]:
third_order_tensor.sum()

234

In [297]:
third_order_tensor.shape

(3, 3, 4)

In [308]:
print('mean(axis = 1)',test_array2.mean(axis=1))
print('mean(axis = 0)',test_array2.mean(axis=0))

mean(axis = 1) [ 2.5  6.5 10.5]
mean(axis = 0) [5. 6. 7. 8.]


In [309]:
print('std(axis = 1)',test_array2.std(axis=1))
print('std(axis = 0)',test_array2.std(axis=0))

std(axis = 1) [1.11803399 1.11803399 1.11803399]
std(axis = 0) [3.26598632 3.26598632 3.26598632 3.26598632]


In [311]:
np.sqrt(test_array2)

array([[1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712],
       [3.        , 3.16227766, 3.31662479, 3.46410162]])

In [312]:
v1 = np.array([1,2,3])
v2 = np.array([4,5,6])
np.vstack((v1,v2))

array([[1, 2, 3],
       [4, 5, 6]])

In [316]:
np.hstack((v1,v2))

array([1, 2, 3, 4, 5, 6])

In [319]:
v1 = v1.reshape(-1,1)
v2 = v2.reshape(-1,1)
print('v1 = ',v1)
print('v2 = ',v2)

v1 =  [[1]
 [2]
 [3]]
v2 =  [[4]
 [5]
 [6]]


In [321]:
v1.shape

(3, 1)

In [320]:
np.hstack((v1,v2))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [322]:
np.vstack((v1,v2))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [343]:
v1 = np.array([[1,2,3]])
v2 = np.array([[4,5,6]])

In [344]:

np.concatenate((v1,v2), axis=0)

array([[1, 2, 3],
       [4, 5, 6]])

In [349]:
v1.reshape(1,-1)

array([[1, 2, 3]])

In [357]:
v3 = np.arange(1,5).reshape(2,2)
v4 = np.arange(5,7).reshape(2,1)

In [358]:
np.concatenate((v3,v4),axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

In [360]:
x = np.arange(1,7).reshape(2,3)
x

array([[1, 2, 3],
       [4, 5, 6]])

In [361]:
x+x

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [362]:
x-x

array([[0, 0, 0],
       [0, 0, 0]])

In [363]:
x*x

array([[ 1,  4,  9],
       [16, 25, 36]])

In [364]:
x/x

array([[1., 1., 1.],
       [1., 1., 1.]])

In [365]:
x**x

array([[    1,     4,    27],
       [  256,  3125, 46656]])

In [366]:
x//x

array([[1, 1, 1],
       [1, 1, 1]])