In [46]:
import cv2
import numpy as np

#1
roi = None
drag_start = None
mouse_status = 0
tracking_start = False
# 4개 변수 초기화, 마우스 이벤트에 사용

# mouse event 함수 정의
def onMouse(event, x, y, flags, param=None):
    global roi
    global drag_start
    global mouse_status
    global tracking_start
    
    if event == cv2.EVENT_LBUTTONDOWN:
        drag_start = (x, y) # 마우스 드래그 포인트
        mouse_status = 1  # 1은 roi를 설정하기 시작했다는 의미
        tracking_start = False # 아직 트랙킹 안 한 상태
        
    elif event == cv2.EVENT_MOUSEMOVE:
        if flags == cv2.EVENT_FLAG_LBUTTON:
            xmin = min(x, drag_start[0])
            ymin = min(y, drag_start[1])
            xmax = max(x, drag_start[0])
            ymax = max(y, drag_start[1])
            roi = (xmin, ymin, xmax, ymax)
            mouse_status = 2 # dragging
            # 마우스 시작포인트, 끝 포인트 즉 roi 영역 저장, 드래그 하는 중이라는 의미
            
    elif event == cv2.EVENT_LBUTTONUP:
        mouse_status = 3 # complete 마우스에서 손을 떼었다라는 의미

In [47]:

cv2.namedWindow('tracking') # tracking 이라는 윈도우 생성
cv2.setMouseCallback('tracking', onMouse) # onMous에 등록


cap = cv2.VideoCapture('/Users/iseung-won/images/lucas2.mp4') # 새로운 영상 읽기
if (not cap.isOpened()):
    print('Error opening video')
    
height, width = (int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT)), 
                 int(cap.get(cv2.CAP_PROP_FRAME_WIDTH)))
roi_mask = np.zeros((height, width), dtype=np.uint8) 
# 동영상과 같은 사이즈의 roi 마스크 생성. black

params = dict(maxCorners=16, qualityLevel=0.1, minDistance=1, blockSize=5)
# 밑에 goodFeaturesToTrack에 사용
term_crit = (cv2.TERM_CRITERIA_MAX_ITER+cv2.TERM_CRITERIA_EPS, 10, 0.01)
# 계속 돌아가지 않게 종료 조건 설정 시 사용, 10번
params2 = dict(winSize=(5,5), maxLevel=3, criteria=term_crit)
# 루카스 카나데 opticalflow 함수에 넣는 파라미터

#3
t = 0
while True:


    ret, frame = cap.read()
    if not ret:
        break
    t += 1
    print('t =', t)
    imgC = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    imgC = cv2.GaussianBlur(imgC, (5,5), 0.0)
    # 프레임 가져와서 gray는 흑백으로 변경 후 가우시안 블러 적용
    
    #3-1
    if mouse_status==2: # 마우스 드래그 중
        x1, y1, x2, y2 = roi
        cv2.rectangle(frame, (x1, y1), (x2, y2), (0,0,255), 2)
    
    #3-2
    if mouse_status==3: # 마우스 손 뗀 상태, roi 설정 완료
        print('initialize...')
        mouse_status = 0
        x1, y1, x2, y2 = roi       # 좌표에 따른 roi 설정
        roi_mask[:, :] = 0         # 원래 블랙 
        roi_mask[y1:y2, x1:x2] = 1 # roi 영역만 1로 셋팅
        p1 = cv2.goodFeaturesToTrack(imgC, mask=roi_mask, **params) # 피처를 찾기 위해 좋은 트랙킹을 찾는다, 최종 피처가 남는다
        if len(p1)>=4:             # 피처가 4개 이상이면
            p1 = cv2.cornerSubPix(imgC, p1, (5,5), (-1,-1), term_crit) # 코너를 찾는다
            rect = cv2.minAreaRect(p1) # 코너가 이루는 최소 사각형 구간
            box_pts = cv2.boxPoints(rect).reshape(-1,1,2) # 포인트로 변경 저장
            tracking_start = True # 트랙킹 시작
            
    #3-3
    if tracking_start: # 트랙킹 시작되었다면,
        p2, st, err = cv2.calcOpticalFlowPyrLK(imgP, imgC, p1, None, **params2) #옵티컬플로우 피라미드 LK
        p1r, st, err = cv2.calcOpticalFlowPyrLK(imgC, imgP, p2, None, **params2)
        # imgC는 가우시안 블러한 현재 프레임, imgP는 현재 프레임을 카피한 것. 반복문이므로 다음 루프 때 이전 루프의 imgC와 동일
        # 즉 imgC는 current frame, imgP는 previous frame
        # p2에 이전 프레임 ~ 현재 프레임 optical flow 저장, p1r에 현재 프레임 ~ 이전 프레임 optical flow 저장
        # 이유는 두 개의 차이가 적어야 optical flow에 문제가 없는 것
        d = abs(p1-p1r).reshape(-1,2).max(-1)
        # 그래서 두 차이를 계산
        stat = d < 1.0 # 1.0 is distance threshold, 차이 기준 1
        good_p2 = p2[stat==1].copy() # p2는 optical flow
        good_p1 = p1[stat==1].copy() # p1은 good feature
        for x, y in good_p2.reshape(-1, 2): # p2에 저장되어 있는 것들을 원으로 표시
            cv2.circle(frame, (int(x), int(y)), 3, (0,0,255), -1)
        
        if len(good_p2)<4: # 4보다 적으면 넘어감
            continue
        
        H, mask = cv2.findHomography(good_p1, good_p2, cv2.RANSAC, 3.0) # p1, p2로 네모 찾음 (매칭)
        box_pts = cv2.perspectiveTransform(box_pts, H) # 찾고자 하는 오브젝트의 바운딩 박스 생성
        cv2.polylines(frame, [np.int32(box_pts)], True, (255,0,0), 2) # 바운딩 박스 그림
        p1 = good_p2.reshape(-1,1,2)
        
    #3-4
    cv2.imshow('tracking', frame)
    imgP = imgC.copy()
    key = cv2.waitKey(25)
    if key == 27:
        break

if cap.isOpened():
    cap.release()
cv2.destroyAllWindows()
cv2.waitKey(1)

t = 1
t = 2
t = 3
t = 4
t = 5
t = 6
t = 7
t = 8
t = 9
t = 10
t = 11
t = 12
t = 13
t = 14
t = 15
t = 16
t = 17
t = 18
t = 19
t = 20
t = 21
t = 22
t = 23
t = 24
t = 25
t = 26
t = 27
t = 28
t = 29
t = 30
t = 31
t = 32
t = 33
t = 34
t = 35
t = 36
t = 37
t = 38
t = 39
t = 40
t = 41
t = 42
t = 43
t = 44
t = 45
t = 46
t = 47
t = 48
t = 49
t = 50
t = 51
t = 52
t = 53
t = 54
t = 55
t = 56
t = 57
t = 58
t = 59
t = 60
t = 61
t = 62
t = 63
t = 64
t = 65
t = 66
t = 67
t = 68
t = 69
t = 70
t = 71
t = 72
t = 73
t = 74
t = 75
t = 76
t = 77
t = 78
t = 79
t = 80
t = 81
t = 82
t = 83
t = 84
t = 85
t = 86
t = 87
t = 88
t = 89
t = 90
t = 91
t = 92
t = 93
t = 94
t = 95
t = 96
t = 97
t = 98
t = 99
t = 100
t = 101
t = 102
t = 103
t = 104
t = 105
t = 106
t = 107
t = 108
t = 109
t = 110
t = 111
t = 112
t = 113
t = 114
t = 115
t = 116
initialize...
t = 117
t = 118
t = 119
initialize...
t = 120
t = 121
t = 122
t = 123
t = 124
t = 125
t = 126
t = 127
t = 128
t = 129
t = 130
t = 131
t = 132
t = 133
t = 134
t = 135


-1

In [43]:
import cv2
import numpy as np

#1
roi = None
drag_start = None
mouse_status = 0
tracking_start = False

# 4개 변수 초기화, 마우스 이벤트에 사용

# mouse event 함수 정의
def onMouse(event, x, y, flags, param=None):
    global roi
    global drag_start
    global mouse_status
    global tracking_start
    
    if event == cv2.EVENT_LBUTTONDOWN:
        drag_start = (x, y) # 마우스 드래그 포인트
        mouse_status = 1  # 1은 roi를 설정하기 시작했다는 의미
        tracking_start = False # 아직 트랙킹 안 한 상태
        
    elif event == cv2.EVENT_MOUSEMOVE:
        if flags == cv2.EVENT_FLAG_LBUTTON:
            xmin = min(x, drag_start[0])
            ymin = min(y, drag_start[1])
            xmax = max(x, drag_start[0])
            ymax = max(y, drag_start[1])
            roi = (xmin, ymin, xmax, ymax)
            mouse_status = 2 # dragging
            # 마우스 시작포인트, 끝 포인트 즉 roi 영역 저장, 드래그 하는 중이라는 의미
            
    elif event == cv2.EVENT_LBUTTONUP:
        mouse_status = 3 # complete 마우스에서 손을 떼었다라는 의미

#2
cv2.namedWindow('tracking') # tracking 이라는 윈도우 생성
cv2.setMouseCallback('tracking', onMouse) # onMous에 등록

path = './'
cap = cv2.VideoCapture('/Users/iseung-won/images/lucas2.mp4') # 새로운 영상 읽기
if (not cap.isOpened()):
    print('Error opening video')
    
height, width = (int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT)), 
                 int(cap.get(cv2.CAP_PROP_FRAME_WIDTH)))
roi_mask = np.zeros((height, width), dtype=np.uint8) 
# 동영상과 같은 사이즈의 roi 마스크 생성. black

params = dict(maxCorners=16, qualityLevel=0.1, minDistance=1, blockSize=5)
# 밑에 goodFeaturesToTrack에 사용
term_crit = (cv2.TERM_CRITERIA_MAX_ITER+cv2.TERM_CRITERIA_EPS, 10, 0.01)
# 계속 돌아가지 않게 종료 조건 설정 시 사용, 10번
params2 = dict(winSize=(5,5), maxLevel=3, criteria=term_crit)
# 루카스 카나데 opticalflow 함수에 넣는 파라미터

#3
t = 0
while True:
    ret, frame = cap.read()
    if not ret:
        break
    t += 1
    print('t =', t)
    imgC = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    imgC = cv2.GaussianBlur(imgC, (5,5), 0.0)
    # 프레임 가져와서 gray는 흑백으로 변경 후 가우시안 블러 적용
    
    #3-1
    if mouse_status==2: # 마우스 드래그 중
        x1, y1, x2, y2 = roi
        cv2.rectangle(frame, (x1, y1), (x2, y2), (0,0,255), 2)
    
    #3-2
    if mouse_status==3: # 마우스 손 뗀 상태, roi 설정 완료
        print('initialize...')
        mouse_status = 0
        x1, y1, x2, y2 = roi       # 좌표에 따른 roi 설정
        roi_mask[:, :] = 0         # 원래 블랙 
        roi_mask[y1:y2, x1:x2] = 1 # roi 영역만 1로 셋팅
        p1 = cv2.goodFeaturesToTrack(imgC, mask=roi_mask, **params) # 피처를 찾기 위해 좋은 트랙킹을 찾는다, 최종 피처가 남는다
        if len(p1)>=4:             # 피처가 4개 이상이면
            p1 = cv2.cornerSubPix(imgC, p1, (5,5), (-1,-1), term_crit) # 코너를 찾는다
            rect = cv2.minAreaRect(p1) # 코너가 이루는 최소 사각형 구간
            box_pts = cv2.boxPoints(rect).reshape(-1,1,2) # 포인트로 변경 저장
            tracking_start = True # 트랙킹 시작
            
    #3-3
    if tracking_start: # 트랙킹 시작되었다면,
        p2, st, err = cv2.calcOpticalFlowPyrLK(imgP, imgC, p1, None, **params2) #옵티컬플로우 피라미드 LK
        p1r, st, err = cv2.calcOpticalFlowPyrLK(imgC, imgP, p2, None, **params2)
        # imgC는 가우시안 블러한 현재 프레임, imgP는 현재 프레임을 카피한 것. 반복문이므로 다음 루프 때 이전 루프의 imgC와 동일
        # 즉 imgC는 current frame, imgP는 previous frame
        # p2에 이전 프레임 ~ 현재 프레임 optical flow 저장, p1r에 현재 프레임 ~ 이전 프레임 optical flow 저장
        # 이유는 두 개의 차이가 적어야 optical flow에 문제가 없는 것
        d = abs(p1-p1r).reshape(-1,2).max(-1)
        # 그래서 두 차이를 계산
        stat = d < 1.0 # 1.0 is distance threshold, 차이 기준 1
        good_p2 = p2[stat==1].copy() # p2는 optical flow
        good_p1 = p1[stat==1].copy() # p1은 good feature
        print('good_p1=',good_p1)
        print('good_p2=',good_p2)
        for x, y in good_p2.reshape(-1, 2): # p2에 저장되어 있는 것들을 원으로 표시
            cv2.circle(frame, (int(x), int(y)), 3, (0,0,255), -1)
        
        if len(good_p2)<4: # 4보다 적으면 넘어감
            continue
        
        H, mask = cv2.findHomography(good_p1, good_p2, cv2.RANSAC, 3.0) # p1, p2로 네모 찾음 (매칭)
        box_pts = cv2.perspectiveTransform(box_pts, H) # 찾고자 하는 오브젝트의 바운딩 박스 생성
        cv2.polylines(frame, [np.int32(box_pts)], True, (255,0,0), 2) # 바운딩 박스 그림
        p1 = good_p2.reshape(-1,1,2)
        
    #3-4
    cv2.imshow('tracking', frame)
    imgP = imgC.copy()
    key = cv2.waitKey(25)
    if key == 27:
        break

if cap.isOpened():
    cap.release()
cv2.destroyAllWindows()
cv2.waitKey(1)

t = 1
t = 2
t = 3
t = 4
t = 5
t = 6
t = 7
t = 8
t = 9
t = 10
t = 11
t = 12
t = 13
t = 14
t = 15
t = 16
t = 17
t = 18
t = 19
t = 20
t = 21
t = 22
t = 23
t = 24
t = 25
t = 26
t = 27
t = 28
t = 29
t = 30
t = 31
t = 32
t = 33
t = 34
t = 35
t = 36
t = 37
t = 38
t = 39
t = 40
t = 41
t = 42
t = 43
t = 44
t = 45
t = 46
t = 47
t = 48
t = 49
t = 50
t = 51
t = 52
t = 53
t = 54
t = 55
t = 56
t = 57
t = 58
t = 59
t = 60
t = 61
t = 62
t = 63
t = 64
t = 65
t = 66
t = 67
t = 68
t = 69
t = 70
t = 71
t = 72
t = 73
t = 74
t = 75
t = 76
t = 77
t = 78
t = 79
t = 80
t = 81
t = 82
t = 83
t = 84
t = 85
t = 86
t = 87
t = 88
t = 89
t = 90
t = 91
t = 92
t = 93
t = 94
t = 95
t = 96
t = 97
t = 98
initialize...
good_p1= [[[ 603.66815 1189.2666 ]]

 [[ 630.42584 1176.2803 ]]

 [[ 622.5323  1187.3119 ]]

 [[ 616.07635 1184.5674 ]]

 [[ 671.4014  1174.8217 ]]

 [[ 625.27893 1177.9714 ]]

 [[ 593.0361  1191.8489 ]]

 [[ 660.8266  1178.8245 ]]

 [[ 619.93475 1188.4235 ]]

 [[ 635.      1187.     ]]

 [[ 631.      1191. 

t = 107
good_p1= [[[ 597.88885 1184.1277 ]]

 [[ 624.6506  1171.2079 ]]

 [[ 616.82666 1182.117  ]]

 [[ 610.32336 1179.5602 ]]

 [[ 665.458   1169.7361 ]]

 [[ 619.4975  1172.9244 ]]

 [[ 587.43994 1186.7288 ]]

 [[ 654.9306  1173.7389 ]]

 [[ 614.1608  1183.2828 ]]

 [[ 629.2548  1181.8036 ]]

 [[ 625.2025  1185.7134 ]]

 [[ 662.3606  1152.2101 ]]

 [[ 652.1264  1157.1719 ]]

 [[ 639.10486 1165.4843 ]]

 [[ 646.1993  1172.8583 ]]

 [[ 634.119   1177.8082 ]]]
good_p2= [[[ 598.65625 1183.9586 ]]

 [[ 625.40186 1171.1919 ]]

 [[ 617.5491  1182.0731 ]]

 [[ 611.10065 1179.3384 ]]

 [[ 666.1527  1169.7074 ]]

 [[ 620.25433 1172.8605 ]]

 [[ 588.2498  1186.6274 ]]

 [[ 655.6519  1173.6238 ]]

 [[ 614.96655 1183.1725 ]]

 [[ 629.9826  1181.7626 ]]

 [[ 625.9309  1185.7344 ]]

 [[ 663.1248  1152.2058 ]]

 [[ 652.70215 1157.1516 ]]

 [[ 639.7812  1165.4636 ]]

 [[ 646.8162  1172.855  ]]

 [[ 634.7452  1177.7465 ]]]
t = 108
good_p1= [[[ 598.65625 1183.9586 ]]

 [[ 625.40186 1171.1919 ]]

 [[ 6

t = 117
good_p1= [[[ 604.17017 1183.8132 ]]

 [[ 630.45966 1171.1138 ]]

 [[ 622.7661  1181.885  ]]

 [[ 616.3877  1179.3494 ]]

 [[ 670.57544 1169.7224 ]]

 [[ 625.3546  1172.668  ]]

 [[ 593.82965 1186.187  ]]

 [[ 660.2337  1173.6068 ]]

 [[ 620.18964 1183.0035 ]]

 [[ 634.9526  1181.5245 ]]

 [[ 631.0222  1185.4867 ]]

 [[ 667.40704 1152.4072 ]]

 [[ 657.39545 1157.2582 ]]

 [[ 644.66724 1165.5105 ]]

 [[ 651.57684 1172.7618 ]]

 [[ 639.6464  1177.5834 ]]]
good_p2= [[[ 604.76575 1184.4161 ]]

 [[ 630.96954 1171.7128 ]]

 [[ 623.2666  1182.4553 ]]

 [[ 616.8487  1179.8121 ]]

 [[ 671.0304  1170.4545 ]]

 [[ 625.9154  1173.4438 ]]

 [[ 594.38226 1186.8899 ]]

 [[ 660.6605  1174.2313 ]]

 [[ 620.6787  1183.5295 ]]

 [[ 635.5046  1182.1824 ]]

 [[ 631.48816 1186.0067 ]]

 [[ 667.96246 1153.1321 ]]

 [[ 657.84534 1157.9883 ]]

 [[ 645.14307 1166.1399 ]]

 [[ 652.09875 1173.4716 ]]

 [[ 640.153   1178.2902 ]]]
t = 118
good_p1= [[[ 604.76575 1184.4161 ]]

 [[ 630.96954 1171.7128 ]]

 [[ 6

t = 127
good_p1= [[[ 608.15106 1186.7643 ]]

 [[ 626.2587  1184.8826 ]]

 [[ 620.0293  1182.3623 ]]

 [[ 672.99493 1173.0284 ]]

 [[ 628.694   1175.975  ]]

 [[ 598.01025 1189.0779 ]]

 [[ 662.8925  1176.9274 ]]

 [[ 623.7712  1185.8799 ]]

 [[ 638.2644  1184.6067 ]]

 [[ 634.28876 1188.2676 ]]

 [[ 670.0967  1156.2148 ]]

 [[ 660.1012  1160.946  ]]

 [[ 647.66626 1168.812  ]]

 [[ 654.47327 1176.0531 ]]

 [[ 642.78986 1180.7627 ]]]
good_p2= [[[ 607.55597 1188.1664 ]]

 [[ 625.62177 1186.2748 ]]

 [[ 619.4657  1183.7296 ]]

 [[ 672.3603  1174.5624 ]]

 [[ 628.225   1177.3162 ]]

 [[ 597.373   1190.488  ]]

 [[ 662.2573  1178.2767 ]]

 [[ 623.13947 1187.2849 ]]

 [[ 637.6469  1186.0144 ]]

 [[ 633.6569  1189.6161 ]]

 [[ 669.2754  1157.6725 ]]

 [[ 659.45746 1162.3751 ]]

 [[ 647.05    1170.2795 ]]

 [[ 653.8968  1177.434  ]]

 [[ 642.1831  1182.1952 ]]]
t = 128
good_p1= [[[ 607.55597 1188.1664 ]]

 [[ 625.62177 1186.2748 ]]

 [[ 619.4657  1183.7296 ]]

 [[ 672.3603  1174.5624 ]]

 [[ 6

t = 137
good_p1= [[[ 617.353   1203.3502 ]]

 [[ 635.33105 1201.5098 ]]

 [[ 629.1463  1198.9987 ]]

 [[ 681.8421  1189.9149 ]]

 [[ 637.922   1192.7037 ]]

 [[ 607.2419  1205.6133 ]]

 [[ 671.7322  1193.6143 ]]

 [[ 632.8257  1202.5385 ]]

 [[ 647.374   1201.3245 ]]

 [[ 643.36255 1204.953  ]]

 [[ 678.8116  1173.091  ]]

 [[ 669.0894  1177.7054 ]]

 [[ 656.64716 1185.6417 ]]

 [[ 663.52234 1192.7716 ]]

 [[ 651.733   1197.4628 ]]]
good_p2= [[[ 617.7798  1203.9823 ]]

 [[ 635.79175 1202.1766 ]]

 [[ 629.6839  1199.5555 ]]

 [[ 682.34076 1190.6604 ]]

 [[ 638.42474 1193.3776 ]]

 [[ 607.6907  1206.3407 ]]

 [[ 672.25836 1194.2987 ]]

 [[ 633.3937  1203.1527 ]]

 [[ 647.8455  1202.0455 ]]

 [[ 643.8718  1205.6597 ]]

 [[ 679.342   1173.818  ]]

 [[ 669.579   1178.4615 ]]

 [[ 657.1865  1186.3651 ]]

 [[ 664.09937 1193.5002 ]]

 [[ 652.2964  1198.2045 ]]]
t = 138
good_p1= [[[ 617.7798  1203.9823 ]]

 [[ 635.79175 1202.1766 ]]

 [[ 629.6839  1199.5555 ]]

 [[ 682.34076 1190.6604 ]]

 [[ 6

t = 147
good_p1= [[[ 609.84503 1203.519  ]]

 [[ 627.8071  1201.7885 ]]

 [[ 621.7126  1199.3606 ]]

 [[ 673.9632  1190.4023 ]]

 [[ 630.1916  1192.9835 ]]

 [[ 599.7309  1205.9717 ]]

 [[ 663.9439  1194.1135 ]]

 [[ 625.39374 1202.7513 ]]

 [[ 639.6674  1201.6079 ]]

 [[ 635.6508  1205.138  ]]

 [[ 671.17737 1173.6018 ]]

 [[ 661.3878  1178.282  ]]

 [[ 649.00287 1186.0154 ]]

 [[ 655.8425  1193.2085 ]]

 [[ 644.08246 1197.837  ]]]
good_p2= [[[ 608.44916 1204.1498 ]]

 [[ 626.38135 1202.3527 ]]

 [[ 620.32965 1199.853  ]]

 [[ 672.66113 1190.8489 ]]

 [[ 628.84424 1193.4512 ]]

 [[ 598.4172  1206.4242 ]]

 [[ 662.5963  1194.5236 ]]

 [[ 623.9754  1203.297  ]]

 [[ 638.2959  1202.1835 ]]

 [[ 634.252   1205.6661 ]]

 [[ 669.7231  1174.249  ]]

 [[ 659.98004 1178.7488 ]]

 [[ 647.54834 1186.4729 ]]

 [[ 654.4124  1193.7133 ]]

 [[ 642.64594 1198.3634 ]]]
t = 148
good_p1= [[[ 608.44916 1204.1498 ]]

 [[ 626.38135 1202.3527 ]]

 [[ 620.32965 1199.853  ]]

 [[ 672.66113 1190.8489 ]]

 [[ 6

t = 157
good_p1= [[[ 607.0034  1203.204  ]]

 [[ 625.0236  1201.3922 ]]

 [[ 618.93915 1198.9161 ]]

 [[ 671.56036 1190.0148 ]]

 [[ 627.54297 1192.5602 ]]

 [[ 597.0108  1205.457  ]]

 [[ 661.49005 1193.6184 ]]

 [[ 622.59064 1202.3845 ]]

 [[ 637.0198  1201.2985 ]]

 [[ 633.0728  1204.8893 ]]

 [[ 668.6146  1173.241  ]]

 [[ 658.8187  1177.8505 ]]

 [[ 646.42584 1185.7262 ]]

 [[ 653.2128  1192.8174 ]]

 [[ 641.3863  1197.4697 ]]]
good_p2= [[[ 607.6155  1202.1887 ]]

 [[ 625.4735  1200.3247 ]]

 [[ 619.37836 1197.7666 ]]

 [[ 672.0906  1188.8057 ]]

 [[ 628.0813  1191.3629 ]]

 [[ 597.47217 1204.4652 ]]

 [[ 662.01825 1192.4452 ]]

 [[ 623.00714 1201.361  ]]

 [[ 637.5049  1200.1234 ]]

 [[ 633.4872  1203.6539 ]]

 [[ 669.172   1171.9353 ]]

 [[ 659.3791  1176.6201 ]]

 [[ 646.93567 1184.5593 ]]

 [[ 653.7075  1191.6019 ]]

 [[ 641.9285  1196.2571 ]]]
t = 158
good_p1= [[[ 607.6155  1202.1887 ]]

 [[ 625.4735  1200.3247 ]]

 [[ 619.37836 1197.7666 ]]

 [[ 672.0906  1188.8057 ]]

 [[ 6

t = 167
good_p1= [[[ 622.2617  1202.702  ]]

 [[ 640.255   1200.921  ]]

 [[ 634.10046 1198.3485 ]]

 [[ 686.84174 1189.3909 ]]

 [[ 642.74884 1191.959  ]]

 [[ 612.0949  1204.9974 ]]

 [[ 676.71295 1193.1017 ]]

 [[ 637.82477 1201.8701 ]]

 [[ 652.2317  1200.6353 ]]

 [[ 648.21606 1204.2784 ]]

 [[ 683.9206  1172.5914 ]]

 [[ 674.1493  1177.1792 ]]

 [[ 661.6032  1185.1094 ]]

 [[ 668.47876 1192.2352 ]]

 [[ 656.6843  1196.8434 ]]]
good_p2= [[[ 625.1663  1202.6786 ]]

 [[ 643.12396 1200.8611 ]]

 [[ 637.0659  1198.3761 ]]

 [[ 689.61096 1189.3395 ]]

 [[ 645.6064  1191.9978 ]]

 [[ 615.0648  1205.001  ]]

 [[ 679.59454 1193.022  ]]

 [[ 640.698   1201.8303 ]]

 [[ 655.109   1200.6387 ]]

 [[ 651.1037  1204.2524 ]]

 [[ 686.69495 1172.5714 ]]

 [[ 676.99115 1177.1552 ]]

 [[ 664.47894 1185.0789 ]]

 [[ 671.3113  1192.2188 ]]

 [[ 659.5046  1196.8168 ]]]
t = 168
good_p1= [[[ 625.1663  1202.6786 ]]

 [[ 643.12396 1200.8611 ]]

 [[ 637.0659  1198.3761 ]]

 [[ 689.61096 1189.3395 ]]

 [[ 6

t = 177
good_p1= [[[ 635.5789  1195.1439 ]]

 [[ 653.5065  1193.291  ]]

 [[ 647.3796  1190.7626 ]]

 [[ 699.8473  1181.6975 ]]

 [[ 656.08673 1184.375  ]]

 [[ 625.47    1197.396  ]]

 [[ 689.85486 1185.3895 ]]

 [[ 651.08765 1194.2743 ]]

 [[ 665.41    1193.0437 ]]

 [[ 661.42944 1196.5353 ]]

 [[ 696.86945 1164.9977 ]]

 [[ 687.13873 1169.6782 ]]

 [[ 674.7341  1177.5127 ]]

 [[ 681.5949  1184.6104 ]]

 [[ 669.89417 1189.2289 ]]]
good_p2= [[[ 636.9319  1193.8794 ]]

 [[ 654.9492  1191.8512 ]]

 [[ 648.79114 1189.4313 ]]

 [[ 701.3118  1180.2698 ]]

 [[ 657.4147  1183.0344 ]]

 [[ 627.01404 1196.0287 ]]

 [[ 691.3035  1183.9242 ]]

 [[ 652.5034  1192.8455 ]]

 [[ 666.837   1191.6237 ]]

 [[ 662.8778  1195.1831 ]]

 [[ 698.2809  1163.6652 ]]

 [[ 688.5005  1168.325  ]]

 [[ 676.1219  1176.1133 ]]

 [[ 682.98846 1183.2456 ]]

 [[ 671.3512  1187.7991 ]]]
t = 178
good_p1= [[[ 636.9319  1193.8794 ]]

 [[ 654.9492  1191.8512 ]]

 [[ 648.79114 1189.4313 ]]

 [[ 701.3118  1180.2698 ]]

 [[ 6

t = 187
good_p1= [[[ 630.6327  1188.0332 ]]

 [[ 648.52985 1185.975  ]]

 [[ 642.46356 1183.6006 ]]

 [[ 694.6312  1174.2566 ]]

 [[ 651.03546 1177.2169 ]]

 [[ 620.6594  1190.3556 ]]

 [[ 684.6547  1177.9625 ]]

 [[ 646.0885  1186.9523 ]]

 [[ 660.42065 1185.6866 ]]

 [[ 656.43915 1189.0687 ]]

 [[ 691.58453 1157.768  ]]

 [[ 681.9242  1162.357  ]]

 [[ 669.65686 1170.1584 ]]

 [[ 676.4544  1177.2095 ]]

 [[ 664.90436 1181.8427 ]]]
good_p2= [[[ 630.9938  1190.0436 ]]

 [[ 649.0022  1188.0859 ]]

 [[ 642.80707 1185.7706 ]]

 [[ 695.1507  1176.4132 ]]

 [[ 651.46686 1179.43   ]]

 [[ 621.13306 1192.4049 ]]

 [[ 685.2112  1179.9713 ]]

 [[ 646.5309  1189.0955 ]]

 [[ 660.8604  1187.8793 ]]

 [[ 656.93634 1191.3083 ]]

 [[ 692.17444 1159.824  ]]

 [[ 682.3712  1164.4508 ]]

 [[ 670.1142  1172.3418 ]]

 [[ 676.9498  1179.302  ]]

 [[ 665.435   1184.0416 ]]]
t = 188
good_p1= [[[ 630.9938  1190.0436 ]]

 [[ 649.0022  1188.0859 ]]

 [[ 642.80707 1185.7706 ]]

 [[ 695.1507  1176.4132 ]]

 [[ 6

t = 197
good_p1= [[[ 597.9856  1202.1313 ]]

 [[ 616.04443 1200.0409 ]]

 [[ 609.77985 1197.7085 ]]

 [[ 662.39404 1187.9583 ]]

 [[ 618.48346 1191.3435 ]]

 [[ 588.05585 1204.4866 ]]

 [[ 652.35    1191.6486 ]]

 [[ 613.4878  1201.1107 ]]

 [[ 627.8865  1199.7858 ]]

 [[ 623.9548  1203.1842 ]]

 [[ 659.39923 1171.4941 ]]

 [[ 649.6173  1176.0981 ]]

 [[ 637.27576 1184.1423 ]]

 [[ 643.949   1191.1432 ]]

 [[ 632.53705 1195.8014 ]]]
good_p2= [[[ 598.4882  1202.7168 ]]

 [[ 616.4603  1200.5656 ]]

 [[ 610.3063  1198.2657 ]]

 [[ 662.78345 1188.461  ]]

 [[ 618.9956  1191.8224 ]]

 [[ 588.274   1205.1327 ]]

 [[ 652.7834  1192.206  ]]

 [[ 613.9338  1201.6086 ]]

 [[ 628.35394 1200.3104 ]]

 [[ 624.3538  1203.557  ]]

 [[ 659.8631  1171.9166 ]]

 [[ 650.14374 1176.5383 ]]

 [[ 637.6902  1184.6646 ]]

 [[ 644.363   1191.6311 ]]

 [[ 632.90765 1196.3376 ]]]
t = 198
good_p1= [[[ 598.4882  1202.7168 ]]

 [[ 616.4603  1200.5656 ]]

 [[ 610.3063  1198.2657 ]]

 [[ 662.78345 1188.461  ]]

 [[ 6

t = 207
good_p1= [[[ 596.0645  1211.8665 ]]

 [[ 614.1361  1209.5905 ]]

 [[ 607.8585  1207.2743 ]]

 [[ 660.48535 1197.3524 ]]

 [[ 616.5526  1200.8777 ]]

 [[ 586.05927 1214.1594 ]]

 [[ 650.50073 1201.0212 ]]

 [[ 611.59375 1210.6561 ]]

 [[ 626.0184  1209.3523 ]]

 [[ 622.08154 1212.7557 ]]

 [[ 657.5299  1180.737  ]]

 [[ 647.6964  1185.4331 ]]

 [[ 635.3345  1193.6095 ]]

 [[ 642.1053  1200.6073 ]]

 [[ 630.5442  1205.3174 ]]]
good_p2= [[[ 595.5873  1212.4657 ]]

 [[ 613.56647 1210.2142 ]]

 [[ 607.35693 1207.871  ]]

 [[ 660.02844 1197.8945 ]]

 [[ 616.04816 1201.47   ]]

 [[ 585.4585  1214.8463 ]]

 [[ 650.08496 1201.6064 ]]

 [[ 611.0081  1211.2954 ]]

 [[ 625.4967  1209.8973 ]]

 [[ 621.50806 1213.2317 ]]

 [[ 657.0757  1181.2974 ]]

 [[ 647.2477  1186.0012 ]]

 [[ 634.9053  1194.2195 ]]

 [[ 641.60486 1201.1488 ]]

 [[ 630.14575 1205.8989 ]]]
t = 208
good_p1= [[[ 595.5873  1212.4657 ]]

 [[ 613.56647 1210.2142 ]]

 [[ 607.35693 1207.871  ]]

 [[ 660.02844 1197.8945 ]]

 [[ 6

t = 217
good_p1= [[[ 592.1987  1218.4921 ]]

 [[ 610.2731  1216.2212 ]]

 [[ 603.97534 1213.8718 ]]

 [[ 656.7367  1203.6814 ]]

 [[ 612.62463 1207.469  ]]

 [[ 582.13916 1220.8228 ]]

 [[ 646.6746  1207.3657 ]]

 [[ 607.7526  1217.2502 ]]

 [[ 622.20825 1215.8503 ]]

 [[ 618.2111  1219.2363 ]]

 [[ 653.75507 1187.1046 ]]

 [[ 643.94495 1191.8442 ]]

 [[ 631.47406 1200.0397 ]]

 [[ 638.1666  1207.0846 ]]

 [[ 626.8764  1211.822  ]]]
good_p2= [[[ 592.3188  1219.3173 ]]

 [[ 610.2924  1217.0122 ]]

 [[ 604.0234  1214.7158 ]]

 [[ 656.7764  1204.5276 ]]

 [[ 612.7034  1208.2982 ]]

 [[ 582.30096 1221.8938 ]]

 [[ 646.7843  1208.2129 ]]

 [[ 607.7654  1218.0677 ]]

 [[ 622.25024 1216.6501 ]]

 [[ 618.26904 1220.0936 ]]

 [[ 653.79395 1187.8348 ]]

 [[ 644.0675  1192.6172 ]]

 [[ 631.57446 1200.8223 ]]

 [[ 638.29083 1207.807  ]]

 [[ 626.8715  1212.6119 ]]]
t = 218
good_p1= [[[ 592.3188  1219.3173 ]]

 [[ 610.2924  1217.0122 ]]

 [[ 604.0234  1214.7158 ]]

 [[ 656.7764  1204.5276 ]]

 [[ 6

t = 227
good_p1= [[[ 592.65234 1229.5057 ]]

 [[ 610.7567  1227.1711 ]]

 [[ 604.4526  1224.7926 ]]

 [[ 657.263   1214.5028 ]]

 [[ 582.5916  1231.8698 ]]

 [[ 647.2809  1218.2356 ]]

 [[ 608.2325  1228.2446 ]]

 [[ 622.6388  1226.756  ]]

 [[ 618.66473 1230.1147 ]]

 [[ 654.2509  1197.8185 ]]

 [[ 644.44116 1202.5687 ]]

 [[ 632.0333  1210.9366 ]]

 [[ 638.6885  1217.808  ]]

 [[ 627.37445 1222.6892 ]]]
good_p2= [[[ 591.8759  1230.2363 ]]

 [[ 610.0391  1227.76   ]]

 [[ 603.70966 1225.4718 ]]

 [[ 656.49896 1215.2146 ]]

 [[ 581.9099  1232.5294 ]]

 [[ 646.5066  1218.9672 ]]

 [[ 607.4744  1228.8646 ]]

 [[ 621.85364 1227.4828 ]]

 [[ 617.8978  1230.8431 ]]

 [[ 653.49207 1198.5757 ]]

 [[ 643.6764  1203.3352 ]]

 [[ 631.2909  1211.582  ]]

 [[ 637.9482  1218.5488 ]]

 [[ 626.6065  1223.3964 ]]]
t = 228
good_p1= [[[ 591.8759  1230.2363 ]]

 [[ 610.0391  1227.76   ]]

 [[ 603.70966 1225.4718 ]]

 [[ 656.49896 1215.2146 ]]

 [[ 581.9099  1232.5294 ]]

 [[ 646.5066  1218.9672 ]]

 [[ 6

t = 242
good_p1= [[[ 602.396   1212.9652 ]]

 [[ 613.9012  1208.397  ]]

 [[ 665.24927 1199.5322 ]]

 [[ 592.22363 1215.4316 ]]

 [[ 655.2842  1203.4344 ]]

 [[ 631.6379  1210.434  ]]

 [[ 627.53394 1214.3319 ]]

 [[ 661.4854  1182.0474 ]]

 [[ 652.22815 1186.7784 ]]

 [[ 647.6767  1201.8326 ]]

 [[ 635.3479  1206.9001 ]]]
good_p2= [[[ 603.0705  1211.0894 ]]

 [[ 614.6794  1206.6606 ]]

 [[ 665.80853 1197.9319 ]]

 [[ 592.9996  1213.6055 ]]

 [[ 655.7801  1201.6865 ]]

 [[ 632.2026  1208.5286 ]]

 [[ 628.1678  1212.6324 ]]

 [[ 662.0757  1180.0361 ]]

 [[ 652.7149  1184.9044 ]]

 [[ 648.2051  1200.0079 ]]

 [[ 635.858   1205.0503 ]]]
t = 243
good_p1= [[[ 603.0705  1211.0894 ]]

 [[ 614.6794  1206.6606 ]]

 [[ 665.80853 1197.9319 ]]

 [[ 592.9996  1213.6055 ]]

 [[ 655.7801  1201.6865 ]]

 [[ 632.2026  1208.5286 ]]

 [[ 628.1678  1212.6324 ]]

 [[ 662.0757  1180.0361 ]]

 [[ 652.7149  1184.9044 ]]

 [[ 648.2051  1200.0079 ]]

 [[ 635.858   1205.0503 ]]]
good_p2= [[[ 605.2041  1210.4802 

t = 262
good_p1= [[[ 533.0779  1206.5839 ]]

 [[ 544.5189  1202.1096 ]]

 [[ 587.2573  1196.2494 ]]

 [[ 522.889   1209.053  ]]

 [[ 561.99176 1203.5602 ]]

 [[ 558.0161  1207.4005 ]]

 [[ 577.8754  1195.006  ]]

 [[ 566.08154 1199.9308 ]]]
good_p2= [[[ 528.9016  1204.1273 ]]

 [[ 540.4743  1199.6741 ]]

 [[ 583.03815 1193.9083 ]]

 [[ 518.9724  1206.5349 ]]

 [[ 557.8398  1201.1959 ]]

 [[ 553.7959  1205.0336 ]]

 [[ 573.73395 1192.5807 ]]

 [[ 561.80286 1197.5325 ]]]
t = 263
good_p1= [[[ 528.9016  1204.1273 ]]

 [[ 540.4743  1199.6741 ]]

 [[ 583.03815 1193.9083 ]]

 [[ 518.9724  1206.5349 ]]

 [[ 557.8398  1201.1959 ]]

 [[ 553.7959  1205.0336 ]]

 [[ 573.73395 1192.5807 ]]

 [[ 561.80286 1197.5325 ]]]
good_p2= [[[ 524.6397  1201.547  ]]

 [[ 536.16675 1196.9744 ]]

 [[ 578.72546 1191.0786 ]]

 [[ 514.5555  1204.0497 ]]

 [[ 553.58594 1198.4691 ]]

 [[ 549.52014 1202.2445 ]]

 [[ 569.4298  1189.806  ]]

 [[ 557.5592  1194.8103 ]]]
t = 264
good_p1= [[[ 524.6397  1201.547  ]]

 [[ 536

t = 282
good_p1= [[[ 501.7247  1135.7451 ]]

 [[ 512.849   1131.2057 ]]

 [[ 554.78485 1124.4565 ]]

 [[ 492.11456 1138.06   ]]

 [[ 530.1037  1132.2632 ]]

 [[ 526.20276 1135.4683 ]]

 [[ 545.6021  1123.6049 ]]

 [[ 534.04645 1128.5111 ]]]
good_p2= [[[ 501.4466  1131.0386 ]]

 [[ 512.66034 1126.5127 ]]

 [[ 554.55304 1119.7227 ]]

 [[ 491.75394 1133.3447 ]]

 [[ 529.8109  1127.4768 ]]

 [[ 525.8724  1130.853  ]]

 [[ 545.29474 1118.8695 ]]

 [[ 533.8334  1123.7634 ]]]
t = 283
good_p1= [[[ 501.4466  1131.0386 ]]

 [[ 512.66034 1126.5127 ]]

 [[ 554.55304 1119.7227 ]]

 [[ 491.75394 1133.3447 ]]

 [[ 529.8109  1127.4768 ]]

 [[ 525.8724  1130.853  ]]

 [[ 545.29474 1118.8695 ]]

 [[ 533.8334  1123.7634 ]]]
good_p2= [[[ 500.5146  1125.8787 ]]

 [[ 511.71698 1121.3186 ]]

 [[ 553.5642  1114.6357 ]]

 [[ 490.9342  1128.1954 ]]

 [[ 528.8226  1122.3805 ]]

 [[ 524.923   1125.712  ]]

 [[ 544.43365 1113.7673 ]]

 [[ 532.9094  1118.6464 ]]]
t = 284
good_p1= [[[ 500.5146  1125.8787 ]]

 [[ 511

t = 302
good_p1= [[[ 505.70874 1060.508  ]]

 [[ 516.786   1056.1835 ]]

 [[ 558.3184  1049.5608 ]]

 [[ 496.32745 1062.6031 ]]

 [[ 533.7464  1057.182  ]]

 [[ 529.8538  1060.0513 ]]

 [[ 549.07794 1048.938  ]]

 [[ 537.87933 1053.4156 ]]]
good_p2= [[[ 506.77075 1058.0775 ]]

 [[ 517.8364  1053.6803 ]]

 [[ 559.3628  1047.1411 ]]

 [[ 497.34735 1060.1813 ]]

 [[ 534.79486 1054.7    ]]

 [[ 530.8477  1057.412  ]]

 [[ 550.14307 1046.4089 ]]

 [[ 538.95074 1050.9589 ]]]
t = 303
good_p1= [[[ 506.77075 1058.0775 ]]

 [[ 517.8364  1053.6803 ]]

 [[ 559.3628  1047.1411 ]]

 [[ 497.34735 1060.1813 ]]

 [[ 534.79486 1054.7    ]]

 [[ 530.8477  1057.412  ]]

 [[ 550.14307 1046.4089 ]]

 [[ 538.95074 1050.9589 ]]]
good_p2= [[[ 507.02148 1054.1094 ]]

 [[ 518.12756 1049.7192 ]]

 [[ 559.44165 1043.1825 ]]

 [[ 497.58572 1056.188  ]]

 [[ 534.95526 1050.704  ]]

 [[ 531.031   1053.4294 ]]

 [[ 550.34607 1042.4194 ]]

 [[ 539.0923  1047.0288 ]]]
t = 304
good_p1= [[[ 507.02148 1054.1094 ]]

 [[ 518

t = 322
good_p1= [[[522.8161  988.43945]]

 [[574.15466 975.91345]]

 [[514.2395  990.4062 ]]

 [[550.24695 983.3558 ]]

 [[546.2898  986.1726 ]]

 [[565.3943  975.02203]]

 [[553.9422  979.75323]]]
good_p2= [[[525.6192  986.5312 ]]

 [[576.9814  973.63544]]

 [[517.03894 988.41595]]

 [[552.9425  981.15295]]

 [[549.0677  983.9551 ]]

 [[568.2053  972.71576]]

 [[556.6828  977.5127 ]]]
t = 323
good_p1= [[[525.6192  986.5312 ]]

 [[576.9814  973.63544]]

 [[517.03894 988.41595]]

 [[552.9425  981.15295]]

 [[549.0677  983.9551 ]]

 [[568.2053  972.71576]]

 [[556.6828  977.5127 ]]]
good_p2= [[[530.2661  984.5171 ]]

 [[581.4071  971.2788 ]]

 [[521.56976 986.53955]]

 [[557.47687 978.8988 ]]

 [[553.5651  981.8331 ]]

 [[572.4983  970.45856]]

 [[561.1415  975.34894]]]
t = 324
good_p1= [[[530.2661  984.5171 ]]

 [[581.4071  971.2788 ]]

 [[521.56976 986.53955]]

 [[557.47687 978.8988 ]]

 [[553.5651  981.8331 ]]

 [[572.4983  970.45856]]

 [[561.1415  975.34894]]]
good_p2= [[[536.18317

t = 347
good_p1= [[[674.1583  958.1797 ]]

 [[724.93384 943.28174]]

 [[665.018   960.8611 ]]

 [[701.71643 952.366  ]]

 [[698.03064 955.8071 ]]

 [[716.075   942.8266 ]]

 [[705.1713  948.77826]]]
good_p2= [[[682.74426 959.95966]]

 [[733.6383  945.0388 ]]

 [[673.546   962.7498 ]]

 [[710.37964 954.1793 ]]

 [[706.6203  957.5163 ]]

 [[724.743   944.68054]]

 [[713.7521  950.59735]]]
t = 348
good_p1= [[[682.74426 959.95966]]

 [[733.6383  945.0388 ]]

 [[673.546   962.7498 ]]

 [[710.37964 954.1793 ]]

 [[706.6203  957.5163 ]]

 [[724.743   944.68054]]

 [[713.7521  950.59735]]]
good_p2= [[[691.12854 962.0779 ]]

 [[741.98016 947.18384]]

 [[682.00586 964.7497 ]]

 [[718.7454  956.2574 ]]

 [[715.0444  959.6357 ]]

 [[733.11505 946.8008 ]]

 [[722.13153 952.684  ]]]
t = 349
good_p1= [[[691.12854 962.0779 ]]

 [[741.98016 947.18384]]

 [[682.00586 964.7497 ]]

 [[718.7454  956.2574 ]]

 [[715.0444  959.6357 ]]

 [[733.11505 946.8008 ]]

 [[722.13153 952.684  ]]]
good_p2= [[[700.33954

t = 372
good_p1= [[[ 859.3742  1057.2834 ]]

 [[ 912.82355 1043.8278 ]]

 [[ 849.674   1060.0765 ]]

 [[ 888.39655 1052.3102 ]]

 [[ 884.6272  1056.2148 ]]

 [[ 903.6656  1042.8627 ]]

 [[ 892.03827 1048.7175 ]]]
good_p2= [[[ 861.6878  1064.6852 ]]

 [[ 915.32355 1051.5342 ]]

 [[ 852.0636  1067.3601 ]]

 [[ 890.76196 1059.8481 ]]

 [[ 887.07245 1063.8855 ]]

 [[ 906.19324 1050.4451 ]]

 [[ 894.4259  1056.2955 ]]]
t = 373
good_p1= [[[ 861.6878  1064.6852 ]]

 [[ 915.32355 1051.5342 ]]

 [[ 852.0636  1067.3601 ]]

 [[ 890.76196 1059.8481 ]]

 [[ 887.07245 1063.8855 ]]

 [[ 906.19324 1050.4451 ]]

 [[ 894.4259  1056.2955 ]]]
good_p2= [[[ 864.2336  1071.9039 ]]

 [[ 917.9785  1059.1134 ]]

 [[ 854.4189  1074.6299 ]]

 [[ 893.347   1067.2124 ]]

 [[ 889.57513 1071.2333 ]]

 [[ 908.67926 1057.9099 ]]

 [[ 896.89154 1063.5945 ]]]
t = 374
good_p1= [[[ 864.2336  1071.9039 ]]

 [[ 917.9785  1059.1134 ]]

 [[ 854.4189  1074.6299 ]]

 [[ 893.347   1067.2124 ]]

 [[ 889.57513 1071.2333 ]]

 [[ 908

t = 392
good_p1= [[[ 874.11646 1240.4363 ]]

 [[ 930.2924  1228.3491 ]]

 [[ 863.87274 1243.2611 ]]

 [[ 904.54065 1236.6245 ]]

 [[ 900.6652  1241.0361 ]]

 [[ 920.64    1227.1124 ]]

 [[ 908.5252  1232.7631 ]]]
good_p2= [[[ 871.3316  1249.3726 ]]

 [[ 927.52344 1237.1426 ]]

 [[ 861.2414  1252.2465 ]]

 [[ 901.77124 1245.5085 ]]

 [[ 897.86145 1249.9839 ]]

 [[ 917.9218  1235.856  ]]

 [[ 905.70557 1241.6185 ]]]
t = 393
good_p1= [[[ 871.3316  1249.3726 ]]

 [[ 927.52344 1237.1426 ]]

 [[ 861.2414  1252.2465 ]]

 [[ 901.77124 1245.5085 ]]

 [[ 897.86145 1249.9839 ]]

 [[ 917.9218  1235.856  ]]

 [[ 905.70557 1241.6185 ]]]
good_p2= [[[ 867.8474  1257.8806 ]]

 [[ 923.9933  1245.5205 ]]

 [[ 857.70905 1260.8615 ]]

 [[ 898.3587  1253.9606 ]]

 [[ 894.5133  1258.3948 ]]

 [[ 914.4715  1244.304  ]]

 [[ 902.28284 1250.1516 ]]]
t = 394
good_p1= [[[ 867.8474  1257.8806 ]]

 [[ 923.9933  1245.5205 ]]

 [[ 857.70905 1260.8615 ]]

 [[ 898.3587  1253.9606 ]]

 [[ 894.5133  1258.3948 ]]

 [[ 914

t = 412
good_p1= [[[ 783.3157  1361.0061 ]]

 [[ 839.8721  1347.1526 ]]

 [[ 772.89264 1364.3354 ]]

 [[ 814.0067  1356.4354 ]]

 [[ 810.1645  1361.4119 ]]

 [[ 830.12805 1346.242  ]]

 [[ 818.06757 1352.4415 ]]]
good_p2= [[[ 777.2181  1365.2622 ]]

 [[ 833.8633  1351.4438 ]]

 [[ 766.89655 1368.5536 ]]

 [[ 807.87384 1360.6746 ]]

 [[ 804.0605  1365.7261 ]]

 [[ 824.0607  1350.4569 ]]

 [[ 811.9998  1356.6777 ]]]
t = 413
good_p1= [[[ 777.2181  1365.2622 ]]

 [[ 833.8633  1351.4438 ]]

 [[ 766.89655 1368.5536 ]]

 [[ 807.87384 1360.6746 ]]

 [[ 804.0605  1365.7261 ]]

 [[ 824.0607  1350.4569 ]]

 [[ 811.9998  1356.6777 ]]]
good_p2= [[[ 771.7289  1369.7078 ]]

 [[ 828.3952  1355.6923 ]]

 [[ 761.23267 1373.1278 ]]

 [[ 802.3998  1365.0209 ]]

 [[ 798.5665  1370.0167 ]]

 [[ 818.57983 1354.6964 ]]

 [[ 806.51697 1361.0531 ]]]
t = 414
good_p1= [[[ 771.7289  1369.7078 ]]

 [[ 828.3952  1355.6923 ]]

 [[ 761.23267 1373.1278 ]]

 [[ 802.3998  1365.0209 ]]

 [[ 798.5665  1370.0167 ]]

 [[ 818

t = 432
good_p1= [[[ 680.535   1449.7917 ]]

 [[ 737.4455  1434.5128 ]]

 [[ 670.19196 1453.2506 ]]

 [[ 711.2709  1444.4907 ]]

 [[ 707.4701  1449.7158 ]]

 [[ 727.5842  1433.6149 ]]

 [[ 715.49634 1440.4341 ]]]
good_p2= [[[ 677.44037 1452.4601 ]]

 [[ 734.31415 1437.296  ]]

 [[ 666.7863  1456.0405 ]]

 [[ 708.178   1447.1531 ]]

 [[ 704.37354 1452.435  ]]

 [[ 724.484   1436.3805 ]]

 [[ 712.3248  1443.1965 ]]]
t = 433
good_p1= [[[ 677.44037 1452.4601 ]]

 [[ 734.31415 1437.296  ]]

 [[ 666.7863  1456.0405 ]]

 [[ 708.178   1447.1531 ]]

 [[ 704.37354 1452.435  ]]

 [[ 724.484   1436.3805 ]]

 [[ 712.3248  1443.1965 ]]]
good_p2= [[[ 673.38165 1454.4236 ]]

 [[ 730.27405 1439.076  ]]

 [[ 662.7974  1458.0234 ]]

 [[ 704.0463  1449.0675 ]]

 [[ 700.28406 1454.3895 ]]

 [[ 720.31274 1438.2482 ]]

 [[ 708.253   1445.1029 ]]]
t = 434
good_p1= [[[ 673.38165 1454.4236 ]]

 [[ 730.27405 1439.076  ]]

 [[ 662.7974  1458.0234 ]]

 [[ 704.0463  1449.0675 ]]

 [[ 700.28406 1454.3895 ]]

 [[ 720

t = 452
good_p1= [[[ 581.4719  1517.1895 ]]

 [[ 638.4327  1499.4802 ]]

 [[ 571.02814 1520.9835 ]]

 [[ 612.3018  1510.204  ]]

 [[ 608.5079  1516.3468 ]]

 [[ 628.5697  1498.6857 ]]

 [[ 616.4263  1506.2935 ]]]
good_p2= [[[ 573.78925 1519.9274 ]]

 [[ 630.7664  1502.16   ]]

 [[ 563.1554  1524.0267 ]]

 [[ 604.55994 1512.8973 ]]

 [[ 600.8353  1519.1501 ]]

 [[ 620.84357 1501.4105 ]]

 [[ 608.7311  1509.0515 ]]]
t = 453
good_p1= [[[ 573.78925 1519.9274 ]]

 [[ 630.7664  1502.16   ]]

 [[ 563.1554  1524.0267 ]]

 [[ 604.55994 1512.8973 ]]

 [[ 600.8353  1519.1501 ]]

 [[ 620.84357 1501.4105 ]]

 [[ 608.7311  1509.0515 ]]]
good_p2= [[[ 565.4539  1521.3201 ]]

 [[ 622.4523  1503.3584 ]]

 [[ 554.9599  1525.215  ]]

 [[ 596.1828  1514.1368 ]]

 [[ 592.449   1520.3276 ]]

 [[ 612.4534  1502.585  ]]

 [[ 600.28876 1510.2703 ]]]
t = 454
good_p1= [[[ 565.4539  1521.3201 ]]

 [[ 622.4523  1503.3584 ]]

 [[ 554.9599  1525.215  ]]

 [[ 596.1828  1514.1368 ]]

 [[ 592.449   1520.3276 ]]

 [[ 612

t = 472
good_p1= [[[ 448.34067 1502.2476 ]]

 [[ 504.49182 1481.9077 ]]

 [[ 438.04337 1506.4188 ]]

 [[ 478.58765 1493.4825 ]]

 [[ 475.0429  1500.1813 ]]

 [[ 494.719   1481.307  ]]

 [[ 482.55353 1489.7006 ]]]
good_p2= [[[ 440.3242  1500.5201 ]]

 [[ 496.42215 1480.1025 ]]

 [[ 429.99146 1504.7034 ]]

 [[ 470.5048  1491.7322 ]]

 [[ 466.9468  1498.4263 ]]

 [[ 486.70557 1479.5061 ]]

 [[ 474.55536 1487.9939 ]]]
t = 473
good_p1= [[[ 440.3242  1500.5201 ]]

 [[ 496.42215 1480.1025 ]]

 [[ 429.99146 1504.7034 ]]

 [[ 470.5048  1491.7322 ]]

 [[ 466.9468  1498.4263 ]]

 [[ 486.70557 1479.5061 ]]

 [[ 474.55536 1487.9939 ]]]
good_p2= [[[ 432.68396 1497.5153 ]]

 [[ 488.65533 1477.0215 ]]

 [[ 422.27557 1501.8778 ]]

 [[ 462.82706 1488.73   ]]

 [[ 459.30978 1495.3346 ]]

 [[ 478.94824 1476.4725 ]]

 [[ 466.88715 1484.9603 ]]]
t = 474
good_p1= [[[ 432.68396 1497.5153 ]]

 [[ 488.65533 1477.0215 ]]

 [[ 422.27557 1501.8778 ]]

 [[ 462.82706 1488.73   ]]

 [[ 459.30978 1495.3346 ]]

 [[ 478

t = 492
good_p1= [[[ 371.5206  1407.7047 ]]

 [[ 426.80365 1386.9137 ]]

 [[ 361.14655 1412.0228 ]]

 [[ 401.36954 1398.4968 ]]

 [[ 397.81403 1405.1278 ]]

 [[ 417.25394 1386.4353 ]]

 [[ 405.13434 1394.8888 ]]]
good_p2= [[[ 368.77463 1402.9225 ]]

 [[ 424.01425 1382.1963 ]]

 [[ 358.41977 1407.2257 ]]

 [[ 398.62634 1393.763  ]]

 [[ 395.0769  1400.3774 ]]

 [[ 414.52637 1381.652  ]]

 [[ 402.35486 1390.1487 ]]]
t = 493
good_p1= [[[ 368.77463 1402.9225 ]]

 [[ 424.01425 1382.1963 ]]

 [[ 358.41977 1407.2257 ]]

 [[ 398.62634 1393.763  ]]

 [[ 395.0769  1400.3774 ]]

 [[ 414.52637 1381.652  ]]

 [[ 402.35486 1390.1487 ]]]
good_p2= [[[ 366.46094 1398.2219 ]]

 [[ 421.68784 1377.3518 ]]

 [[ 356.26178 1402.3866 ]]

 [[ 396.29965 1389.0426 ]]

 [[ 392.70697 1395.5364 ]]

 [[ 412.19662 1376.8536 ]]

 [[ 400.02475 1385.3743 ]]]
t = 494
good_p1= [[[ 366.46094 1398.2219 ]]

 [[ 421.68784 1377.3518 ]]

 [[ 356.26178 1402.3866 ]]

 [[ 396.29965 1389.0426 ]]

 [[ 392.70697 1395.5364 ]]

 [[ 412

t = 512
good_p1= [[[ 362.2843  1306.6383 ]]

 [[ 416.7409  1286.094  ]]

 [[ 352.39978 1310.5083 ]]

 [[ 391.6355  1297.8517 ]]

 [[ 388.1062  1303.6023 ]]

 [[ 407.1782  1286.0566 ]]

 [[ 395.5947  1293.836  ]]]
good_p2= [[[ 362.7523  1299.8237 ]]

 [[ 417.20074 1279.4487 ]]

 [[ 353.06726 1303.5212 ]]

 [[ 392.13947 1291.1407 ]]

 [[ 388.5616  1296.7258 ]]

 [[ 407.66165 1279.3198 ]]

 [[ 396.14145 1287.1135 ]]]
t = 513
good_p1= [[[ 362.7523  1299.8237 ]]

 [[ 417.20074 1279.4487 ]]

 [[ 353.06726 1303.5212 ]]

 [[ 392.13947 1291.1407 ]]

 [[ 388.5616  1296.7258 ]]

 [[ 407.66165 1279.3198 ]]

 [[ 396.14145 1287.1135 ]]]
good_p2= [[[ 363.69482 1293.5618 ]]

 [[ 418.08057 1273.1157 ]]

 [[ 353.879   1297.3136 ]]

 [[ 392.98193 1284.798  ]]

 [[ 389.46054 1290.3386 ]]

 [[ 408.50568 1273.091  ]]

 [[ 397.05    1280.7498 ]]]
t = 514
good_p1= [[[ 363.69482 1293.5618 ]]

 [[ 418.08057 1273.1157 ]]

 [[ 353.879   1297.3136 ]]

 [[ 392.98193 1284.798  ]]

 [[ 389.46054 1290.3386 ]]

 [[ 408

t = 532
good_p1= [[[ 410.50415 1233.6122 ]]

 [[ 464.34937 1212.7952 ]]

 [[ 400.8785  1237.2666 ]]

 [[ 439.52686 1225.0293 ]]

 [[ 436.02853 1229.9412 ]]

 [[ 454.5658  1213.3461 ]]

 [[ 443.73364 1220.7238 ]]]
good_p2= [[[ 416.05298 1232.8099 ]]

 [[ 469.82196 1212.1023 ]]

 [[ 406.30182 1236.5514 ]]

 [[ 445.0874  1224.32   ]]

 [[ 441.5114  1229.0927 ]]

 [[ 460.14365 1212.5548 ]]

 [[ 449.31857 1219.9728 ]]]
t = 533
good_p1= [[[ 416.05298 1232.8099 ]]

 [[ 469.82196 1212.1023 ]]

 [[ 406.30182 1236.5514 ]]

 [[ 445.0874  1224.32   ]]

 [[ 441.5114  1229.0927 ]]

 [[ 460.14365 1212.5548 ]]

 [[ 449.31857 1219.9728 ]]]
good_p2= [[[ 423.5297  1233.2639 ]]

 [[ 477.43988 1212.6812 ]]

 [[ 413.70584 1236.9198 ]]

 [[ 452.52658 1224.7543 ]]

 [[ 448.98682 1229.6714 ]]

 [[ 467.5458  1213.1492 ]]

 [[ 456.65485 1220.472  ]]]
t = 534
good_p1= [[[ 423.5297  1233.2639 ]]

 [[ 477.43988 1212.6812 ]]

 [[ 413.70584 1236.9198 ]]

 [[ 452.52658 1224.7543 ]]

 [[ 448.98682 1229.6714 ]]

 [[ 467

t = 552
good_p1= [[[ 517.7837  1215.8651 ]]

 [[ 572.2121  1198.3258 ]]

 [[ 508.03488 1219.0862 ]]

 [[ 547.09705 1209.0629 ]]

 [[ 543.37396 1213.7538 ]]

 [[ 562.5573  1198.2871 ]]

 [[ 551.2567  1204.9099 ]]]
good_p2= [[[ 527.0894  1209.1018 ]]

 [[ 581.4802  1191.7777 ]]

 [[ 517.31616 1212.378  ]]

 [[ 556.40967 1202.4072 ]]

 [[ 552.6109  1207.093  ]]

 [[ 571.8486  1191.6978 ]]

 [[ 560.4328  1198.3054 ]]]
t = 553
good_p1= [[[ 527.0894  1209.1018 ]]

 [[ 581.4802  1191.7777 ]]

 [[ 517.31616 1212.378  ]]

 [[ 556.40967 1202.4072 ]]

 [[ 552.6109  1207.093  ]]

 [[ 571.8486  1191.6978 ]]

 [[ 560.4328  1198.3054 ]]]
good_p2= [[[ 535.7846  1203.216  ]]

 [[ 590.27527 1186.2173 ]]

 [[ 526.07635 1206.3258 ]]

 [[ 565.14685 1196.7015 ]]

 [[ 561.366   1201.2876 ]]

 [[ 580.60187 1186.1036 ]]

 [[ 569.16394 1192.6196 ]]]
t = 554
good_p1= [[[ 535.7846  1203.216  ]]

 [[ 590.27527 1186.2173 ]]

 [[ 526.07635 1206.3258 ]]

 [[ 565.14685 1196.7015 ]]

 [[ 561.366   1201.2876 ]]

 [[ 580

t = 572
good_p1= [[[ 615.6249  1189.9348 ]]

 [[ 670.73517 1175.2496 ]]

 [[ 605.5353  1192.8618 ]]

 [[ 645.4509  1184.6951 ]]

 [[ 641.49493 1189.2802 ]]

 [[ 661.2966  1174.626  ]]

 [[ 649.379   1180.9205 ]]]
good_p2= [[[ 619.63666 1193.3511 ]]

 [[ 674.73956 1178.7094 ]]

 [[ 609.6754  1196.22   ]]

 [[ 649.2665  1188.0244 ]]

 [[ 645.3856  1192.6454 ]]

 [[ 665.05383 1178.0868 ]]

 [[ 653.2422  1184.2197 ]]]
t = 573
good_p1= [[[ 619.63666 1193.3511 ]]

 [[ 674.73956 1178.7094 ]]

 [[ 609.6754  1196.22   ]]

 [[ 649.2665  1188.0244 ]]

 [[ 645.3856  1192.6454 ]]

 [[ 665.05383 1178.0868 ]]

 [[ 653.2422  1184.2197 ]]]
good_p2= [[[ 622.4699  1196.1354 ]]

 [[ 677.564   1181.6195 ]]

 [[ 612.3912  1199.0465 ]]

 [[ 652.1075  1190.847  ]]

 [[ 648.267   1195.496  ]]

 [[ 667.91455 1180.8862 ]]

 [[ 656.1342  1187.0479 ]]]
t = 574
good_p1= [[[ 622.4699  1196.1354 ]]

 [[ 677.564   1181.6195 ]]

 [[ 612.3912  1199.0465 ]]

 [[ 652.1075  1190.847  ]]

 [[ 648.267   1195.496  ]]

 [[ 667

t = 592
good_p1= [[[ 664.733   1295.9799 ]]

 [[ 720.6031  1280.1494 ]]

 [[ 654.5924  1299.1573 ]]

 [[ 694.8785  1290.1656 ]]

 [[ 691.14215 1295.2659 ]]

 [[ 710.8327  1279.5509 ]]

 [[ 698.8639  1286.2188 ]]]
good_p2= [[[ 668.16003 1302.2042 ]]

 [[ 723.94885 1286.1978 ]]

 [[ 658.14355 1305.3447 ]]

 [[ 698.2828  1296.2102 ]]

 [[ 694.47516 1301.3376 ]]

 [[ 714.1528  1285.589  ]]

 [[ 702.1693  1292.2992 ]]]
t = 593
good_p1= [[[ 668.16003 1302.2042 ]]

 [[ 723.94885 1286.1978 ]]

 [[ 658.14355 1305.3447 ]]

 [[ 698.2828  1296.2102 ]]

 [[ 694.47516 1301.3376 ]]

 [[ 714.1528  1285.589  ]]

 [[ 702.1693  1292.2992 ]]]
good_p2= [[[ 670.16077 1306.2052 ]]

 [[ 725.7515  1289.8594 ]]

 [[ 660.19855 1309.4075 ]]

 [[ 700.14996 1300.1234 ]]

 [[ 696.41064 1305.243  ]]

 [[ 715.9963  1289.3445 ]]

 [[ 704.04944 1296.2107 ]]]
t = 594
good_p1= [[[ 670.16077 1306.2052 ]]

 [[ 725.7515  1289.8594 ]]

 [[ 660.19855 1309.4075 ]]

 [[ 700.14996 1300.1234 ]]

 [[ 696.41064 1305.243  ]]

 [[ 715

t = 612
good_p1= [[[ 661.9585  1311.5608 ]]

 [[ 717.5536  1295.1366 ]]

 [[ 651.9787  1314.7871 ]]

 [[ 691.8951  1305.3329 ]]

 [[ 688.2239  1310.544  ]]

 [[ 707.84314 1294.5303 ]]

 [[ 695.9853  1301.3597 ]]]
good_p2= [[[ 659.9301  1312.2859 ]]

 [[ 715.70355 1296.1262 ]]

 [[ 649.88727 1315.4493 ]]

 [[ 690.09784 1306.3356 ]]

 [[ 686.3608  1311.3333 ]]

 [[ 706.01556 1295.541  ]]

 [[ 694.14606 1302.3264 ]]]
t = 613
good_p1= [[[ 659.9301  1312.2859 ]]

 [[ 715.70355 1296.1262 ]]

 [[ 649.88727 1315.4493 ]]

 [[ 690.09784 1306.3356 ]]

 [[ 686.3608  1311.3333 ]]

 [[ 706.01556 1295.541  ]]

 [[ 694.14606 1302.3264 ]]]
good_p2= [[[ 659.05786 1311.9774 ]]

 [[ 714.82086 1295.8619 ]]

 [[ 649.0178  1315.0968 ]]

 [[ 689.11816 1306.0459 ]]

 [[ 685.41833 1311.1696 ]]

 [[ 705.14905 1295.2504 ]]

 [[ 693.2702  1302.0723 ]]]
t = 614
good_p1= [[[ 659.05786 1311.9774 ]]

 [[ 714.82086 1295.8619 ]]

 [[ 649.0178  1315.0968 ]]

 [[ 689.11816 1306.0459 ]]

 [[ 685.41833 1311.1696 ]]

 [[ 705

t = 632
good_p1= [[[ 643.46204 1317.0214 ]]

 [[ 699.44086 1300.6326 ]]

 [[ 633.19965 1320.2894 ]]

 [[ 673.57916 1310.8798 ]]

 [[ 669.793   1316.1327 ]]

 [[ 689.65625 1300.189  ]]

 [[ 677.7456  1306.9033 ]]]
good_p2= [[[ 641.02216 1319.3354 ]]

 [[ 696.92145 1302.9355 ]]

 [[ 630.9165  1322.5396 ]]

 [[ 671.12103 1313.3196 ]]

 [[ 667.31616 1318.5062 ]]

 [[ 687.26117 1302.4358 ]]

 [[ 675.19995 1309.3224 ]]]
t = 633
good_p1= [[[ 641.02216 1319.3354 ]]

 [[ 696.92145 1302.9355 ]]

 [[ 630.9165  1322.5396 ]]

 [[ 671.12103 1313.3196 ]]

 [[ 667.31616 1318.5062 ]]

 [[ 687.26117 1302.4358 ]]

 [[ 675.19995 1309.3224 ]]]
good_p2= [[[ 639.04755 1320.9862 ]]

 [[ 694.82477 1304.4066 ]]

 [[ 628.9266  1324.2905 ]]

 [[ 669.0347  1314.8016 ]]

 [[ 665.27637 1320.186  ]]

 [[ 685.0254  1303.9764 ]]

 [[ 673.086   1310.8363 ]]]
t = 634
good_p1= [[[ 639.04755 1320.9862 ]]

 [[ 694.82477 1304.4066 ]]

 [[ 628.9266  1324.2905 ]]

 [[ 669.0347  1314.8016 ]]

 [[ 665.27637 1320.186  ]]

 [[ 685

t = 652
good_p1= [[[ 585.636   1348.6592 ]]

 [[ 636.20337 1334.9354 ]]

 [[ 576.5213  1351.3173 ]]

 [[ 612.7978  1344.1791 ]]

 [[ 609.3925  1349.2871 ]]

 [[ 627.23444 1333.9507 ]]

 [[ 616.0549  1340.4545 ]]]
good_p2= [[[ 583.62115 1349.3951 ]]

 [[ 633.9299  1336.0508 ]]

 [[ 574.6422  1352.2651 ]]

 [[ 610.6509  1344.9982 ]]

 [[ 607.33936 1350.1677 ]]

 [[ 624.9019  1334.9772 ]]

 [[ 613.789   1341.3716 ]]]
t = 653
good_p1= [[[ 583.62115 1349.3951 ]]

 [[ 633.9299  1336.0508 ]]

 [[ 574.6422  1352.2651 ]]

 [[ 610.6509  1344.9982 ]]

 [[ 607.33936 1350.1677 ]]

 [[ 624.9019  1334.9772 ]]

 [[ 613.789   1341.3716 ]]]
good_p2= [[[ 580.1241 1349.2637]]

 [[ 630.4163 1335.9492]]

 [[ 571.2013 1352.0446]]

 [[ 607.1622 1345.0088]]

 [[ 603.8009 1350.1549]]

 [[ 621.4399 1334.9578]]

 [[ 610.2945 1341.3843]]]
t = 654
good_p1= [[[ 580.1241 1349.2637]]

 [[ 630.4163 1335.9492]]

 [[ 571.2013 1352.0446]]

 [[ 607.1622 1345.0088]]

 [[ 603.8009 1350.1549]]

 [[ 621.4399 1334.9578]]

 [[ 6

t = 672
good_p1= [[[ 550.0446  1365.1647 ]]

 [[ 593.2442  1356.8278 ]]

 [[ 542.4612  1367.1191 ]]

 [[ 573.6764  1363.7251 ]]

 [[ 570.72125 1368.1294 ]]

 [[ 585.4425  1354.9893 ]]

 [[ 575.7931  1360.3392 ]]]
good_p2= [[[ 550.18353 1365.4382 ]]

 [[ 593.23126 1357.0459 ]]

 [[ 542.6033  1367.2979 ]]

 [[ 573.66595 1363.9669 ]]

 [[ 570.71027 1368.3501 ]]

 [[ 585.4773  1355.2292 ]]

 [[ 575.78094 1360.5654 ]]]
t = 673
good_p1= [[[ 550.18353 1365.4382 ]]

 [[ 593.23126 1357.0459 ]]

 [[ 542.6033  1367.2979 ]]

 [[ 573.66595 1363.9669 ]]

 [[ 570.71027 1368.3501 ]]

 [[ 585.4773  1355.2292 ]]

 [[ 575.78094 1360.5654 ]]]
good_p2= [[[ 549.50635 1365.0957 ]]

 [[ 592.4696  1356.818  ]]

 [[ 542.27325 1367.0958 ]]

 [[ 573.0897  1363.6532 ]]

 [[ 570.1975  1368.206  ]]

 [[ 584.6374  1355.1089 ]]

 [[ 575.0395  1360.3625 ]]]
t = 674
good_p1= [[[ 549.50635 1365.0957 ]]

 [[ 592.4696  1356.818  ]]

 [[ 542.27325 1367.0958 ]]

 [[ 573.0897  1363.6532 ]]

 [[ 570.1975  1368.206  ]]

 [[ 584

t = 692
good_p1= [[[ 544.195   1356.6923 ]]

 [[ 588.42725 1346.6971 ]]

 [[ 536.4378  1358.809  ]]

 [[ 568.3153  1354.4095 ]]

 [[ 565.2379  1358.9203 ]]

 [[ 580.41925 1345.5754 ]]

 [[ 570.697   1351.0099 ]]]
good_p2= [[[ 544.43414 1356.1804 ]]

 [[ 588.8724  1346.3768 ]]

 [[ 536.7105  1358.2877 ]]

 [[ 568.57605 1353.8964 ]]

 [[ 565.5004  1358.355  ]]

 [[ 580.74457 1344.9701 ]]

 [[ 570.994   1350.425  ]]]
t = 693
good_p1= [[[ 544.43414 1356.1804 ]]

 [[ 588.8724  1346.3768 ]]

 [[ 536.7105  1358.2877 ]]

 [[ 568.57605 1353.8964 ]]

 [[ 565.5004  1358.355  ]]

 [[ 580.74457 1344.9701 ]]

 [[ 570.994   1350.425  ]]]
good_p2= [[[ 544.5155  1355.7626 ]]

 [[ 589.1874  1345.8185 ]]

 [[ 536.8758  1357.8087 ]]

 [[ 568.8242  1353.4457 ]]

 [[ 565.66266 1357.8335 ]]

 [[ 581.0313  1344.4791 ]]

 [[ 571.39996 1349.8536 ]]]
t = 694
good_p1= [[[ 544.5155  1355.7626 ]]

 [[ 589.1874  1345.8185 ]]

 [[ 536.8758  1357.8087 ]]

 [[ 568.8242  1353.4457 ]]

 [[ 565.66266 1357.8335 ]]

 [[ 581

t = 712
good_p1= [[[ 568.9206  1324.6445 ]]

 [[ 620.72974 1309.3823 ]]

 [[ 559.546   1327.8469 ]]

 [[ 596.63324 1319.1393 ]]

 [[ 593.1758  1324.438  ]]

 [[ 611.5878  1308.4706 ]]

 [[ 600.0758  1315.2914 ]]]
good_p2= [[[ 570.94275 1323.8358 ]]

 [[ 623.0667  1308.1768 ]]

 [[ 561.5407  1326.8391 ]]

 [[ 598.86743 1318.0918 ]]

 [[ 595.4123  1323.4382 ]]

 [[ 613.8278  1307.312  ]]

 [[ 602.3583  1314.2451 ]]]
t = 713
good_p1= [[[ 570.94275 1323.8358 ]]

 [[ 623.0667  1308.1768 ]]

 [[ 561.5407  1326.8391 ]]

 [[ 598.86743 1318.0918 ]]

 [[ 595.4123  1323.4382 ]]

 [[ 613.8278  1307.312  ]]

 [[ 602.3583  1314.2451 ]]]
good_p2= [[[ 571.4114  1322.9419 ]]

 [[ 623.5729  1306.9229 ]]

 [[ 562.1032  1325.973  ]]

 [[ 599.4509  1317.0948 ]]

 [[ 595.8796  1322.4059 ]]

 [[ 614.3571  1306.0779 ]]

 [[ 602.92316 1313.1501 ]]]
t = 714
good_p1= [[[ 571.4114  1322.9419 ]]

 [[ 623.5729  1306.9229 ]]

 [[ 562.1032  1325.973  ]]

 [[ 599.4509  1317.0948 ]]

 [[ 595.8796  1322.4059 ]]

 [[ 614

t = 732
good_p1= [[[ 574.73047 1295.162  ]]

 [[ 630.5264  1279.4857 ]]

 [[ 564.65485 1298.2651 ]]

 [[ 604.5671  1288.9303 ]]

 [[ 600.69666 1294.3724 ]]

 [[ 620.7887  1278.2715 ]]

 [[ 608.4186  1285.0972 ]]]
good_p2= [[[ 576.7183  1292.1508 ]]

 [[ 632.68384 1276.9014 ]]

 [[ 566.5561  1295.1705 ]]

 [[ 606.64417 1286.1077 ]]

 [[ 602.73883 1291.4293 ]]

 [[ 623.00793 1275.5729 ]]

 [[ 610.42303 1282.2972 ]]]
t = 733
good_p1= [[[ 576.7183  1292.1508 ]]

 [[ 566.5561  1295.1705 ]]

 [[ 606.64417 1286.1077 ]]

 [[ 602.73883 1291.4293 ]]

 [[ 623.00793 1275.5729 ]]

 [[ 610.42303 1282.2972 ]]]
good_p2= [[[ 576.7817  1292.4752 ]]

 [[ 566.455   1295.5829 ]]

 [[ 606.751   1286.3568 ]]

 [[ 602.85016 1291.7771 ]]

 [[ 623.0111  1275.8351 ]]

 [[ 610.4921  1282.5469 ]]]
t = 734
good_p1= [[[ 576.7817  1292.4752 ]]

 [[ 566.455   1295.5829 ]]

 [[ 606.751   1286.3568 ]]

 [[ 602.85016 1291.7771 ]]

 [[ 623.0111  1275.8351 ]]

 [[ 610.4921  1282.5469 ]]]
good_p2= [[[ 578.3615  1292.8136 ]]

t = 757
good_p1= [[[ 543.4307  1286.8197 ]]

 [[ 533.0326  1289.4352 ]]

 [[ 573.9006  1282.6709 ]]

 [[ 569.73804 1287.7506 ]]

 [[ 590.7397  1273.0411 ]]

 [[ 578.12146 1278.9264 ]]]
good_p2= [[[ 543.9072  1286.7654 ]]

 [[ 533.3685  1289.509  ]]

 [[ 574.4456  1282.4254 ]]

 [[ 570.30035 1287.4568 ]]

 [[ 591.4561  1272.7332 ]]

 [[ 578.5913  1278.64   ]]]
t = 758
good_p1= [[[ 543.9072  1286.7654 ]]

 [[ 533.3685  1289.509  ]]

 [[ 574.4456  1282.4254 ]]

 [[ 570.30035 1287.4568 ]]

 [[ 591.4561  1272.7332 ]]

 [[ 578.5913  1278.64   ]]]
good_p2= [[[ 545.46063 1286.0085 ]]

 [[ 535.0063  1288.6392 ]]

 [[ 575.9621  1281.3948 ]]

 [[ 571.8395  1286.5153 ]]

 [[ 592.78094 1271.5072 ]]

 [[ 580.0965  1277.6193 ]]]
t = 759
good_p1= [[[ 545.46063 1286.0085 ]]

 [[ 535.0063  1288.6392 ]]

 [[ 575.9621  1281.3948 ]]

 [[ 571.8395  1286.5153 ]]

 [[ 592.78094 1271.5072 ]]

 [[ 580.0965  1277.6193 ]]]
good_p2= [[[ 545.93396 1284.4933 ]]

 [[ 535.4576  1287.4603 ]]

 [[ 576.4887  1279.723  ]]

t = 782
good_p1= [[[ 572.09674 1271.2491 ]]

 [[ 561.87384 1274.0011 ]]

 [[ 601.1008  1267.8523 ]]

 [[ 597.3273  1272.9362 ]]

 [[ 616.1328  1258.8461 ]]

 [[ 604.3904  1264.3624 ]]]
good_p2= [[[ 574.1317  1268.9575 ]]

 [[ 564.0348  1271.6166 ]]

 [[ 602.90533 1265.8022 ]]

 [[ 599.21094 1270.7281 ]]

 [[ 617.76794 1256.8794 ]]

 [[ 606.1697  1262.3364 ]]]
t = 783
good_p1= [[[ 574.1317  1268.9575 ]]

 [[ 564.0348  1271.6166 ]]

 [[ 602.90533 1265.8022 ]]

 [[ 599.21094 1270.7281 ]]

 [[ 617.76794 1256.8794 ]]

 [[ 606.1697  1262.3364 ]]]
good_p2= [[[ 576.4387  1267.5043 ]]

 [[ 566.21826 1270.1604 ]]

 [[ 605.0143  1264.3373 ]]

 [[ 601.32477 1269.2336 ]]

 [[ 619.78845 1255.42   ]]

 [[ 608.2336  1260.8508 ]]]
t = 784
good_p1= [[[ 576.4387  1267.5043 ]]

 [[ 566.21826 1270.1604 ]]

 [[ 605.0143  1264.3373 ]]

 [[ 601.32477 1269.2336 ]]

 [[ 619.78845 1255.42   ]]

 [[ 608.2336  1260.8508 ]]]
good_p2= [[[ 578.71686 1266.7255 ]]

 [[ 568.61053 1269.2969 ]]

 [[ 607.1207  1263.6061 ]]

t = 812
good_p1= [[[ 640.9301  1213.411  ]]

 [[ 659.22424 1219.1515 ]]

 [[ 660.317   1224.9441 ]]

 [[ 666.22986 1216.5066 ]]

 [[ 659.4456  1217.8323 ]]]
good_p2= [[[ 641.6774  1213.4114 ]]

 [[ 659.69403 1218.8868 ]]

 [[ 660.7493  1224.7369 ]]

 [[ 666.66473 1216.3601 ]]

 [[ 659.9471  1217.6068 ]]]
t = 813
good_p1= [[[ 641.6774  1213.4114 ]]

 [[ 659.69403 1218.8868 ]]

 [[ 660.7493  1224.7369 ]]

 [[ 666.66473 1216.3601 ]]

 [[ 659.9471  1217.6068 ]]]
good_p2= [[[ 642.0797  1212.8275 ]]

 [[ 660.06256 1218.5269 ]]

 [[ 661.1616  1224.3187 ]]

 [[ 666.73456 1215.914  ]]

 [[ 660.2806  1217.2379 ]]]
t = 814
good_p1= [[[ 642.0797  1212.8275 ]]

 [[ 660.06256 1218.5269 ]]

 [[ 661.1616  1224.3187 ]]

 [[ 666.73456 1215.914  ]]

 [[ 660.2806  1217.2379 ]]]
good_p2= [[[ 642.91504 1212.3959 ]]

 [[ 661.13794 1218.2189 ]]

 [[ 662.3453  1223.8986 ]]

 [[ 667.71906 1215.4968 ]]

 [[ 661.3243  1216.8384 ]]]
t = 815
good_p1= [[[ 642.91504 1212.3959 ]]

 [[ 661.13794 1218.2189 ]]

 [[ 662.3

t = 842
good_p1= [[[ 618.7826  1241.1681 ]]

 [[ 617.2866  1246.4974 ]]

 [[ 632.1293  1232.9708 ]]

 [[ 619.23926 1238.2684 ]]]
good_p2= [[[ 616.3352  1241.6436 ]]

 [[ 614.7395  1246.9686 ]]

 [[ 629.8605  1233.2113 ]]

 [[ 616.78186 1238.6002 ]]]
t = 843
good_p1= [[[ 616.3352  1241.6436 ]]

 [[ 614.7395  1246.9686 ]]

 [[ 629.8605  1233.2113 ]]

 [[ 616.78186 1238.6002 ]]]
good_p2= [[[ 612.8809 1241.9396]]

 [[ 611.3169 1247.1908]]

 [[ 626.8085 1233.2772]]

 [[ 613.4765 1238.6497]]]
t = 844
good_p1= [[[ 612.8809 1241.9396]]

 [[ 611.3169 1247.1908]]

 [[ 626.8085 1233.2772]]

 [[ 613.4765 1238.6497]]]
good_p2= [[[ 610.5455  1241.2616 ]]

 [[ 608.8416  1246.2942 ]]

 [[ 624.67206 1232.1721 ]]

 [[ 611.0421  1237.6664 ]]]
t = 845
good_p1= [[[ 610.5455  1241.2616 ]]

 [[ 608.8416  1246.2942 ]]

 [[ 624.67206 1232.1721 ]]

 [[ 611.0421  1237.6664 ]]]
good_p2= [[[ 610.15015 1240.6366 ]]

 [[ 608.3801  1245.5503 ]]

 [[ 624.6503  1231.3085 ]]

 [[ 610.63727 1236.8145 ]]]
t = 846
good_p1=

good_p1= []
good_p2= []
t = 916
good_p1= []
good_p2= []
t = 917
good_p1= []
good_p2= []
t = 918
good_p1= []
good_p2= []
t = 919
good_p1= []
good_p2= []
t = 920
good_p1= []
good_p2= []
t = 921
good_p1= []
good_p2= []
t = 922
good_p1= []
good_p2= []
t = 923
good_p1= []
good_p2= []
t = 924
good_p1= []
good_p2= []
t = 925
good_p1= []
good_p2= []
t = 926
good_p1= [[[ 550.30927 1250.8104 ]]

 [[ 547.3188  1254.3508 ]]

 [[ 552.49274 1245.7832 ]]]
good_p2= [[[ 524.64606 1272.9294 ]]

 [[ 521.4962  1276.3872 ]]

 [[ 527.0442  1268.109  ]]]
t = 927
good_p1= [[[ 550.30927 1250.8104 ]]

 [[ 547.3188  1254.3508 ]]

 [[ 552.49274 1245.7832 ]]]
good_p2= [[[ 523.53503 1272.0984 ]]

 [[ 520.39215 1275.6633 ]]

 [[ 525.9036  1267.3247 ]]]
t = 928
good_p1= [[[ 550.30927 1250.8104 ]]

 [[ 552.49274 1245.7832 ]]]
good_p2= [[[ 522.4699 1270.4963]]

 [[ 524.6961 1265.7732]]]
t = 929
good_p1= [[[ 550.30927 1250.8104 ]]

 [[ 552.49274 1245.7832 ]]]
good_p2= [[[ 521.5176 1268.5201]]

 [[ 523.7648 1263.9609]]]


t = 1179
good_p1= []
good_p2= []
t = 1180
good_p1= []
good_p2= []
t = 1181
good_p1= []
good_p2= []
t = 1182
good_p1= []
good_p2= []
t = 1183
good_p1= []
good_p2= []
t = 1184
good_p1= []
good_p2= []
t = 1185
good_p1= []
good_p2= []
t = 1186
good_p1= []
good_p2= []
t = 1187
good_p1= []
good_p2= []
t = 1188
good_p1= []
good_p2= []
t = 1189
good_p1= []
good_p2= []
t = 1190
good_p1= []
good_p2= []
t = 1191
good_p1= []
good_p2= []
t = 1192
good_p1= []
good_p2= []
t = 1193
good_p1= []
good_p2= []
t = 1194
good_p1= []
good_p2= []
t = 1195
good_p1= []
good_p2= []
t = 1196
good_p1= []
good_p2= []
t = 1197
good_p1= []
good_p2= []
t = 1198
good_p1= []
good_p2= []
t = 1199
good_p1= []
good_p2= []
t = 1200
good_p1= []
good_p2= []
t = 1201
good_p1= []
good_p2= []
t = 1202
good_p1= []
good_p2= []
t = 1203
good_p1= []
good_p2= []
t = 1204
good_p1= []
good_p2= []
t = 1205
good_p1= []
good_p2= []
t = 1206
good_p1= []
good_p2= []
t = 1207
good_p1= []
good_p2= []
t = 1208
good_p1= []
good_p2= []
t = 1209
g

-1