In [1]:
import numpy as np

In [4]:
arr = np.array([1,2,3])
print('1차원 배열 생성 \n', arr)
arr = np.array([[1,2,3],[4,5,6]])
print('2차원 배렬 생성 \n', arr)

1차원 배열 생성 
 [1 2 3]
2차원 배렬 생성
 [[1 2 3]
 [4 5 6]]


In [8]:
tpl = (4,5,6)
arr = np.array(tpl)
print('튜플로 넘파이 배열 생성 \n', arr, type(arr))
lst = [[1,2,3],
       [4,5,6],
       [7,8,9]]
arr = np.array(lst)
print('리스트로 넘파이 배열 생성 \n', arr, type(arr))

튜플로 넘파이 배열 생성 
 [4 5 6] <class 'numpy.ndarray'>
리스트로 넘파이 배열 생성 
 [[1 2 3]
 [4 5 6]
 [7 8 9]] <class 'numpy.ndarray'>


In [19]:
arr1 = np.array([1,2,3])
arr2 = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])

print('1차원 배열 shape 확인 \n', arr1.shape)
print('\n2차원 배열 shape 확인 \n', arr2.shape)
print('\n 차원 갯수 \n arr1 =', arr1.ndim, '\n arr2 =', arr2.ndim)
print('\n 사이즈 \n arr1 =', arr1.size, '\n arr2 =', arr2.size)

1차원 배열 shape 확인 
 (3,)

2차원 배열 shape 확인 
 (3, 3)

 차원 갯수 
 arr1 = 1 
 arr2 = 2

 사이즈 
 arr1 = 3 
 arr2 = 9


In [23]:
arr = np.array([1,2,3], dtype=np.float64)
print(arr.dtype)
print(arr)

float64
[1. 2. 3.]


In [25]:
arr = np.array([0,1,2], dtype=np.bool_)
print(arr, arr.dtype)

[False  True  True] bool


In [27]:
arr = np.array([0,1,2,3])
print(arr.dtype)
print(arr)
arr = arr.astype(np.float32)
print(arr.dtype)
print(arr)

int64
[0 1 2 3]
float32
[0. 1. 2. 3.]


In [28]:
arr = np.array([1,2,3,4.5])
print(arr, arr.dtype)

[1.  2.  3.  4.5] float64


In [29]:
arr = np.array([1,2,3,'4.5'])
print(arr, arr.dtype)

['1' '2' '3' '4.5'] <U21


In [31]:
arr = np.array([1,2,3,'4'], dtype=int)
print(arr, arr.dtype)

[1 2 3 4] int64


In [32]:
# 에러 발생

arr = np.array([1,2,3,'문자'], dtype=int)
print(arr, arr.dtype)

ValueError: invalid literal for int() with base 10: '문자'

In [34]:
arr = np.zeros([5,5,5])
print(arr)

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


In [37]:
arr = np.ones([3,2,5])
print(arr)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


In [38]:
arr = np.full((3,4), 10)
print(arr)

[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


In [45]:
arr = np.eye(5,5)
print(arr)
arr = np.eye(5,5, k=2)
print(arr)
arr = np.eye(5,5, k=-2)
print(arr)
arr = np.eye(3) # n값만 입력시 n값과 m값 모두 3이 됨
print(arr)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [51]:
arr = np.array([[1,2,3],
                [4,5,6]])

arr_z = np.zeros_like(arr) #행과 열의 갯수가 동일한 원소가 0인 배열을 만듬
print('arr \n', arr)
print('zero_like \n', arr_z)
arr_o = np.ones_like(arr) #행과 열의 갯수가 동일한 원소가 1인 배열을 만듬
print('ones_like \n', arr_o)
arr_f = np.full_like(arr, 21)
print('full_like \n', arr_f)

arr 
 [[1 2 3]
 [4 5 6]]
zero_like 
 [[0 0 0]
 [0 0 0]]
ones_like 
 [[1 1 1]
 [1 1 1]]
full_like 
 [[21 21 21]
 [21 21 21]]
